In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("weatherHistory.csv")

In [3]:
df.head(5)

Formatted Date        Summary Precip Type  Temperature (C)  \
0  2006-04-01 00:00:00.000 +0200  Partly Cloudy        rain         9.472222   
1  2006-04-01 01:00:00.000 +0200  Partly Cloudy        rain         9.355556   
2  2006-04-01 02:00:00.000 +0200  Mostly Cloudy        rain         9.377778   
3  2006-04-01 03:00:00.000 +0200  Partly Cloudy        rain         8.288889   
4  2006-04-01 04:00:00.000 +0200  Mostly Cloudy        rain         8.755556   

   Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0                  7.388889      0.89            14.1197   
1                  7.227778      0.86            14.2646   
2                  9.377778      0.89             3.9284   
3                  5.944444      0.83            14.1036   
4                  6.977778      0.83            11.0446   

   Wind Bearing (degrees)  Visibility (km)  Loud Cover  Pressure (millibars)  \
0                   251.0          15.8263         0.0               1015.13   
1                   259.0          15.8263         0.0               1015.63   
2                   204.0          14.9569         0.0               1015.94   
3                   269.0          15.8263         0.0               1016.41   
4                   259.0          15.8263         0.0               1016.51   

                       Daily Summary  
0  Partly cloudy throughout the day.  
1  Partly cloudy throughout the day.  
2  Partly cloudy throughout the day.  
3  Partly cloudy throughout the day.  
4  Partly cloudy throughout the day.

In [4]:
caty = "Precip Type"
cony = "Temperature (C)"
x = "Humidity"

In [5]:
df.isnull().sum()

Formatted Date                0
Summary                       0
Precip Type                 517
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Loud Cover                    0
Pressure (millibars)          0
Daily Summary                 0
dtype: int64

In [6]:
df = df.dropna()

In [7]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(df)

In [8]:
trainX = train[x]
cattrainy = train[caty]
contrainy = train[cony]
testX = test[x]
cattesty = test[caty]
contesty = test[cony]

In [9]:
trainX = np.array(trainX)
cattrainy = np.array(cattrainy)
contrainy = np.array(contrainy)
testX = np.array(testX)
cattesty = np.array(cattesty)
contesty = np.array(contesty)

In [10]:
trainX = trainX.reshape(-1, 1)
cattrainy = cattrainy.reshape(-1, 1)
contrainy = contrainy.reshape(-1, 1)
testX = testX.reshape(-1, 1)
cattesty = cattesty.reshape(-1, 1)
contesty = contesty.reshape(-1, 1)

In [11]:
from sklearn.isotonic import IsotonicRegression
from sklearn.datasets import make_regression

In [12]:
isox, isoy = make_regression(n_samples=10, n_features=1, random_state=41)

In [13]:
m = IsotonicRegression()

In [14]:
m.fit(isox, isoy)

IsotonicRegression()

In [15]:
m.predict(testX)

array([10.61808924,  4.65705668,         nan, ..., 13.03975872,
       12.85347645, 11.17693604])

In [16]:
from sklearn.datasets import make_sparse_coded_signal
from sklearn.linear_model import OrthogonalMatchingPursuit
n_components, n_features = 550, 100
n_nonzero_coefs = 10

# y = Xw
# |x|_0 = n_nonzero_coefs

y, X, w = make_sparse_coded_signal(n_samples=1,
                                   n_components=n_components,
                                   n_features=n_features,
                                   n_nonzero_coefs=n_nonzero_coefs,
                                   random_state=0)

idx, = w.nonzero()

In [17]:
y_noisy = y + 0.05 * np.random.randn(len(y))

In [18]:
omp = OrthogonalMatchingPursuit(n_nonzero_coefs=n_nonzero_coefs)
omp.fit(X, y)
coef = omp.coef_
idx_r, = coef.nonzero()

In [19]:
 from sklearn import linear_model
reg = linear_model.LassoLars(alpha=0.01)

In [20]:
reg.fit(trainX, contrainy)

LassoLars(alpha=0.01)

In [21]:
reg.predict(testX)

array([14.79477563, 20.32307101,  9.43923948, ..., 12.54890563,
       12.72166486, 14.27649794])

In [23]:
reg = linear_model.Lars()

In [24]:
reg.fit(trainX, contrainy)

Lars()

In [25]:
reg.predict(testX)

array([17.06070436, 26.97508266,  7.45615037, ..., 13.03298817,
       13.34281249, 16.13123139])

In [26]:
from sklearn.linear_model import SGDRegressor

In [28]:
m = SGDRegressor()

In [29]:
m.fit(trainX, contrainy)

/usr/local/lib64/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SGDRegressor()

In [30]:
m.predict(testX)

array([17.11798548, 26.99521984,  7.54941469, ..., 13.10535902,
       13.41402259, 16.19199476])

In [32]:
from sklearn.linear_model import HuberRegressor

In [33]:
m = HuberRegressor()
m.fit(trainX, contrainy)
m.predict(testX)

/usr/local/lib64/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([17.74560477, 28.35977598,  7.46312641, ..., 13.43359771,
       13.76529056, 16.75052622])

In [37]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(2)
poly.fit_transform(trainX)

array([[1.    , 0.77  , 0.5929],
       [1.    , 0.58  , 0.3364],
       [1.    , 0.87  , 0.7569],
       ...,
       [1.    , 0.79  , 0.6241],
       [1.    , 0.45  , 0.2025],
       [1.    , 0.55  , 0.3025]])

In [41]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(trainX, contrainy)
reg.predict(testX)

array([[17.06070436],
       [26.97508266],
       [ 7.45615037],
       ...,
       [13.03298817],
       [13.34281249],
       [16.13123139]])

In [42]:
reg.coef_

array([[-30.98243221]])

In [43]:
from sklearn.svm import NuSVR
m = NuSVR()
m.fit(trainX, contrainy)
m.predict(testX)

/usr/local/lib64/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


KeyboardInterrupt: 

In [44]:
from sklearn.linear_model import MultiTaskLasso
m = MultiTaskLasso()
m.fit(trainX, contrainy)
m.predict(testX)

array([[12.74421937],
       [14.30332115],
       [11.23383952],
       ...,
       [12.11083427],
       [12.1595562 ],
       [12.59805358]])

In [45]:
from sklearn.svm import LinearSVC
m = LinearSVC()
m.fit(trainX, cattrainy)
m.predict(testX)

/usr/local/lib64/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array(['rain', 'rain', 'rain', ..., 'rain', 'rain', 'rain'], dtype=object)

In [46]:
from sklearn.linear_model import SGDClassifier
m = SGDClassifier()
m.fit(trainX, cattrainy)
m.predict(testX)

/usr/local/lib64/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array(['rain', 'rain', 'rain', ..., 'rain', 'rain', 'rain'], dtype='<U4')

In [49]:
from sklearn.naive_bayes import BernoulliNB
m = BernoulliNB()
m.fit(trainX, cattrainy)
m.predict(testX)

/usr/local/lib64/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array(['rain', 'rain', 'rain', ..., 'rain', 'rain', 'rain'], dtype='<U4')

In [50]:
from sklearn.linear_model import RidgeClassifier
m = RidgeClassifier()
m.fit(trainX, cattrainy)
m.predict(testX)

/usr/local/lib64/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array(['rain', 'rain', 'rain', ..., 'rain', 'rain', 'rain'], dtype='<U4')

In [51]:
from sklearn.naive_bayes import GaussianNB
from sklearn.calibration import CalibratedClassifierCV
base_clf = GaussianNB()
calibrated_clf = CalibratedClassifierCV(base_estimator=base_clf, cv=3)

In [52]:
calibrated_clf.fit(trainX, cattrainy)
calibrated_clf.predict(testX)

/usr/local/lib64/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array(['rain', 'rain', 'rain', ..., 'rain', 'rain', 'rain'], dtype=object)