## 10  unusual reasons why julia is awesome!
Hello, my name emmy, and I have been using Julia for around 5-6 years now. I originally came across Julia while researching a problem I was having in C. I am a Data Scientist, so given that Julia is primarily targeted at Scientific computing I was interested in the language. Within the first few months of picking up the language, it  quickly became my favorite programming language. While what you might have heard about Julia's more prominent features, or simply Julia's speed, the language has a lot more to offer than these typical talking points, so I wanted to look at some of my favorite features in Julia that you might not have heard about before!

### Parameterized Types

In [1]:
vs = ["my", "string", "vector"]
vi = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [3]:
function concatvec(vs::Vector{String})
    join(vs)
end

concatvec (generic function with 2 methods)

In [2]:
function concatvec(vi::Vector{Int64})
    sum(vi)
end

concatvec (generic function with 1 method)

In [4]:
concatvec(vi)

6

In [5]:
concatvec(vs)

"mystringvector"

In [6]:
function concatvec(vi::Vector{<:Number})
    sum(vi)
end

concatvec (generic function with 3 methods)

In [7]:
Float64 <: Number

true

In [8]:
concatvec([5.5, 5.5])

11.0

### outside-in methodology

In [9]:
mutable struct MyStruct
    x::Int64
    y::Int64
end

In [10]:
function addstrs(ms::MyStruct, ms2::MyStruct)
    MyStruct(ms.x + ms2.x, ms.y + ms2.y)
end

addstrs (generic function with 1 method)

### closures can be fields

In [11]:
mutable struct OOP
    f::Function
    function OOP()
        x = 5
       f() = begin
           println("yay!") 
        end
        new(f)::OOP
    end
end

In [12]:
oop = OOP()

OOP(var"#f#1"())

In [13]:
oop.f()

yay!


### everything can be introspected

In [14]:
names(Main)

10-element Vector{Symbol}:
 :Base
 :Core
 :Main
 :MyStruct
 :OOP
 :addstrs
 :concatvec
 :oop
 :vi
 :vs

In [17]:
methods(concatvec)[1].sig

Tuple{typeof(concatvec), Vector{Int64}}

In [18]:
fieldnames(OOP)

(:f,)

### (most) functions can be extended

In [19]:
import Base: *

In [21]:
*() = begin
    
end

* (generic function with 365 methods)

In [22]:
*()

In [23]:
import Core: getfield

In [24]:
getfield(x::Any, b::String) = begin
    
end

LoadError: cannot add methods to a builtin function

### a consistent ecosystem

In [25]:
eachcol

eachcol (generic function with 1 method)

In [26]:
eachrow

eachrow (generic function with 1 method)

### built in documentation

In [27]:
?eachrow

search: eachrow searchsorted searchsortedlast searchsortedfirst



```
eachrow(A::AbstractVecOrMat)
```

Create a generator that iterates over the first dimension of vector or matrix `A`, returning the rows as `AbstractVector` views.

See also [`eachcol`](@ref), [`eachslice`](@ref), [`mapslices`](@ref).

!!! compat "Julia 1.1"
    This function requires at least Julia 1.1.


# Example

```jldoctest
julia> a = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> first(eachrow(a))
2-element view(::Matrix{Int64}, 1, :) with eltype Int64:
 1
 2

julia> collect(eachrow(a))
2-element Vector{SubArray{Int64, 1, Matrix{Int64}, Tuple{Int64, Base.Slice{Base.OneTo{Int64}}}, true}}:
 [1, 2]
 [3, 4]
```


### an AWESOME REPL

### Pkg

### broadcasting (is really easy)

In [28]:
broadcast!

broadcast! (generic function with 1 method)

In [29]:
broadcast

broadcast (generic function with 17 methods)

In [32]:
[1, 2, 3] .* [1, 2, 3]

3-element Vector{Int64}:
 1
 4
 9