In [14]:
using DataFrames
df = DataFrame("A" => [1, 2, 3], "B" => [1, 2, 3])
vec = [1, 2, 3]

println(filter!(x -> x == 3, vec))
filter!(row -> row["A"] != 1, df)

[3]


2×2 DataFrame
 Row │ A      B     
     │ Int64  Int64 
─────┼──────────────
   1 │     2      2
   2 │     3      3

### findfirst

In [2]:
position = findfirst(x -> x == "hi", ["hello", "hello", "hi", "bye"])

3

In [3]:
import Base: getindex, in

struct Employee
    name::String
end

in(emps::Vector{Employee}, name::String) = begin
    found = findfirst(emp::Employee -> emp.name == name, emps)
    if isnothing(found)
        return(false)
     end
     return(true)
end

getindex(emps::Vector{Employee}, name::String) = begin
    found = findfirst(emp -> emp.name == name, emps)
    if isnothing(found)
        throw(KeyError([emp.name for emp in emps], name))
    end
    emps[found]
end

getindex (generic function with 319 methods)

In [15]:
rawtext = "hello!\n how are you doing?\n I am well, and you?\n"

findfirst("\n", rawtext)

7:7

### filter

In [16]:
arr = [1, 2, 3, 4, 5, 6]

# Keep only even numbers, returns a new array
evens = filter(x -> x % 2 == 0, arr)

println(evens)  
# [2, 4, 6]
println(arr)    
# [1, 2, 3, 4, 5, 6]

[2, 4, 6]
[1, 2, 3, 4, 5, 6]


In [17]:
arr = [1, 2, 3, 4, 5, 6]

# Keep only even numbers, modifying original array
filter!(x -> x % 2 == 0, arr)

println(arr)  # [2, 4, 6]

[2, 4, 6]


### findall

In [19]:
function n_employees_named(employees::Vector{Employee}, name::String = "steve")
    length(findall(emp::Employee -> emp.name == name))
end

n_employees_named (generic function with 2 methods)

In [20]:
rawhtml = """<!DOCTYPE html>
<html lang="en" id="html1">
<head id="head1">
  <title id="title1">Small Page</title>
</head>
<body id="body1">
  <h1 id="header1">Hello World</h1>
  <p id="para1">This is a paragraph.</p>
  <a href="#" id="link1">Click me</a>
</body>
</html>
"""

"<!DOCTYPE html>\n<html lang=\"en\" id=\"html1\">\n<head id=\"head1\">\n  <title id=\"title1\">Small Page</title>\n</head>\n<body id=\"body1\">\n  <h1 id=\"header1\">Hello World</h1>\n  <p id=\"para1\">This is a paragraph.</p>\n  <a href=\"#\" id=\"link1\">Click me</a>\n</body>\n</html>\n"

In [22]:
all_ids = [begin 
    start_quot = maximum(idpos)
    finish = findnext("\"", rawhtml, start_quot + 1)
    if isnothing(finish)
        throw("invalid HTML")
    end
    # note -- not unicode safe
    rawhtml[start_quot + 1:minimum(finish) - 1]
end for idpos in findall("id=\"", rawhtml)]

7-element Vector{String}:
 "html1"
 "head1"
 "title1"
 "body1"
 "header1"
 "para1"
 "link1"

### replace

In [23]:
s = "hello world"
s2 = replace(s, "world" => "Julia")
println(s2)  # "hello Julia"

v = [1, 2, 3, 2, 4]
v2 = replace(v, 2 => 99)
println(v2)  
# [1, 99, 3, 99, 4]

hello Julia
[1, 99, 3, 99, 4]


In [24]:
v = [1, 2, 3, 2, 4]
replace!(v, 2 => 99)
println(v)  

# [1, 99, 3, 99, 4]

[1, 99, 3, 99, 4]


### split

In [26]:
path = "/path/to/my/stuff"

top_directory = split(path, "/")[2]

"path"

### parse

In [27]:
parse(Int64, "5")

5

In [28]:
parse(Bool, "1")

parse(Bool, "false")

parse(Float64, "1.5")

1.5

In [31]:
value = parse(UInt16, "0010011101100100", base = 2)

println(Char(value))

❤


### tryparse

In [33]:
str1 = "123"
str2 = "abc"

x = tryparse(Int, str1)
y = tryparse(Int, str2)

println(x)  
println(y)  

if y === nothing
    println("Parsing failed for str2")
end

123
nothing
Parsing failed for str2


In [40]:
function is_numerical(s::AbstractString)
    nums = ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9')
    found = findfirst(x::Char -> x in nums, s)
    if isnothing(found)
        return(false)
    end
    return(true)
end

function is_numericalf(s::AbstractString)
    nums = ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '.')
    found = findfirst(x::Char -> x in nums, s)
    if isnothing(found)
        return(false)
    end
    return(true)
end

function assume_parse(s::AbstractString)
    val = nothing
    if is_numericalf(s)
        val = tryparse(Float64, s)
    elseif is_numerical(s)
        val = tryparse(Int64, s)
    end
    if isnothing(val)
        return(string(s))
    end
    val
end

assume_parse (generic function with 1 method)

In [41]:
assume_parse("25") + assume_parse("5.5")

30.5

### unique

In [42]:
arr = [1, 2, 2, 3, 3, 3, 4]
new_arr = unique(arr)

println("Original array: ", arr)
println("Unique array: ", new_arr)

Original array: [1, 2, 2, 3, 3, 3, 4]
Unique array: [1, 2, 3, 4]


In [43]:
arr = [1, 2, 2, 3, 3, 3, 4]
unique!(arr)

println("Modified original array: ", arr)

Modified original array: [1, 2, 3, 4]


In [44]:
vec = map(c for c in "example") do char
    Int8(char)
end

7-element Vector{Int8}:
 101
 120
  97
 109
 112
 108
 101

In [45]:
vec = map([1, 2, 3]) do num
    num += 1
end

3-element Vector{Int64}:
 2
 3
 4

In [46]:
# Preallocate an array to store results
dest = zeros(Int, 5)    # destination array
src  = 1:5              # source data

# Square each element of src and store in dest
map!(x -> x^2, dest, src)

println(dest)  # [1, 4, 9, 16, 25]

[1, 4, 9, 16, 25]


### convert + promote

In [48]:
p::Int64 = 55

newint::Int16 = convert(Int16, p)

55

In [49]:
a = 3         # Int
b = 2.5       # Float64

promote(a, b) 
# returns (3.0, 2.5) with type Tuple{Float64, Float64}

(3.0, 2.5)

### reduce

In [50]:
nums = [1, 2, 3, 4]

result = reduce(+, nums)
println(result)  

result = reduce((x::Int64, y::Int64) -> x += y, nums)

10


10

In [51]:
nums = [24, 36, 60, 48]

result = reduce(gcd, nums)

println(result)  
# 12

12


In [52]:
sum_minus_1(nums::Vector{<:Real}) = reduce(+, nums, init = -1)

sum_minus_1 (generic function with 1 method)

### sort

In [56]:
arr = [3, 1, 4, 2]
sorted_arr = sort(arr)

println(arr)       
println(sorted_arr) 

[3, 1, 4, 2]
[1, 2, 3, 4]


In [57]:
arr = [3, 1, 4, 2]
sort!(arr)

println(arr)  

[1, 2, 3, 4]


### any + all

In [58]:
in(emps::Vector{Employee}, name::String) = begin
    any(emp -> emp.name == name, emps)
end

in (generic function with 62 methods)

In [59]:
all_the_same_name(emps::Vector{Employee}, name::String) = begin
    all(emp -> emp.name == name, emps)
end

all_the_same_name (generic function with 1 method)

In [64]:
display("text/markdown", """# $(Char(value))
    thanks for reading loves c: have a good day""")

# ❤
thanks for reading loves c: have a good day