In [2]:
typeof([1 2; 3 4])

Matrix{Int64} (alias for Array{Int64, 2})

In [3]:
typeof([1, 2, 3])

Vector{Int64} (alias for Array{Int64, 1})

In [ ]:
Vector{Number}([5.5, 5])

In [4]:
[5.5, 5]

2-element Vector{Float64}:
 5.5
 5.0

In [5]:
[5, "six"]

2-element Vector{Any}:
 5
  "six"

In [6]:
myvec = [1, 2, 3, 4]

myvec[1]
1

1

In [8]:
myvec[1:3]

3-element Vector{Int64}:
 1
 2
 3

In [9]:
mvec = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [10]:
mvec[1, 1]

1

In [11]:
mvec[1:2, 1:1]

2×1 Matrix{Int64}:
 1
 3

In [12]:
import Base: getindex

In [13]:
getindex(vs::Vector{String}, i::String) = begin
    pos = findfirst(n -> n == i, vs)
    vs[pos]
end

getindex (generic function with 227 methods)

In [14]:
myvec = ["emmy", "hank", "jon"]

3-element Vector{String}:
 "emmy"
 "hank"
 "jon"

In [15]:
myvec["emmy"]

"emmy"

In [16]:
for x in myvec
   x = x * " is their name"
end

In [19]:
map(myvec) do s::String
   splts::Vector{SubString} = split(s, " ")
   s = string(splts[1])
end

3-element Vector{String}:
 "emmy"
 "hank"
 "jon"

In [21]:
myvec = [s * "is their name" for s in myvec]

3-element Vector{String}:
 "emmyis their name"
 "hankis their name"
 "jonis their name"

In [22]:
for (e, x) in enumerate([1, 2, 3])

end

x = ["$f$s" for (f, s) in zip([1, 2, 3], [1, 2, 3])]

3-element Vector{String}:
 "11"
 "22"
 "33"

In [23]:
using Statistics
x = [5, 10, 15, 20]
mu = mean(x)
sigma = std(x)

x_scaled = [(mu - xbar) / sigma for xbar in x]

[ Info: Precompiling Statistics [10745b16-79ce-11e8-11f9-7d13ad32a3b2]


4-element Vector{Float64}:
  1.161895003862225
  0.3872983346207417
 -0.3872983346207417
 -1.161895003862225

In [24]:
push!(x, 25, 30)

6-element Vector{Int64}:
  5
 10
 15
 20
 25
 30

In [25]:
push!(x, [35, 40])

LoadError: MethodError: Cannot `convert` an object of type Vector{Int64} to an object of type Int64

Closest candidates are:
  convert(::Type{T}, ::T) where T<:Number
   @ Base number.jl:6
  convert(::Type{T}, ::Number) where T<:Number
   @ Base number.jl:7
  convert(::Type{T}, ::Base.TwicePrecision) where T<:Number
   @ Base twiceprecision.jl:273
  ...


In [26]:
append!(x, [35, 40])

8-element Vector{Int64}:
  5
 10
 15
 20
 25
 30
 25
 30

In [28]:
deleteat!(x, 2)

7-element Vector{Int64}:
  5
 15
 20
 25
 30
 25
 30

In [29]:
vcat([5, 10], [50, 60])

4-element Vector{Int64}:
  5
 10
 50
 60

In [41]:
mat = hcat([1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12])
vector = [5, 8, 7, 3]

4-element Vector{Int64}:
 5
 8
 7
 3

In [42]:
size(mat)

(3, 4)

In [43]:
size(vector)

(4,)

In [44]:
reshape(vector, (1, 4))

1×4 Matrix{Int64}:
 5  8  7  3

In [47]:
mat

3×4 Matrix{Int64}:
 1  4  7  10
 2  5  8  11
 3  6  9  12

In [46]:
reshape(mat, (4, 3))

4×3 Matrix{Int64}:
 1  5   9
 2  6  10
 3  7  11
 4  8  12

In [51]:
findfirst(x -> x == 5, mat)

CartesianIndex(2, 2)

In [54]:
filter(x -> x > 7, vector)

1-element Vector{Int64}:
 8

In [55]:
println("len: ", length(mat), " sum: ", sum(mat))

len: 12 sum: 78


In [56]:
[1 5; 2 8] .* [5 2; 4 3]

2×2 Matrix{Int64}:
 5  10
 8  24

In [57]:
function sample(x)
    @info x
end

sample (generic function with 1 method)

In [60]:
sample.(mat)

[ Info: 1
[ Info: 2
[ Info: 3
[ Info: 4
[ Info: 5
[ Info: 6
[ Info: 7
[ Info: 8
[ Info: 9
[ Info: 10
[ Info: 11
[ Info: 12


3×4 Matrix{Nothing}:
 nothing  nothing  nothing  nothing
 nothing  nothing  nothing  nothing
 nothing  nothing  nothing  nothing

In [61]:
transpose(mat)

4×3 transpose(::Matrix{Int64}) with eltype Int64:
  1   2   3
  4   5   6
  7   8   9
 10  11  12

In [62]:
using LinearAlgebra

#### DataFrames

In [66]:
using DataFrames

In [67]:
df = DataFrame(:x => [1, 2, 3], :b => [20.2, 30.5, 30.0])

3×2 DataFrame
 Row │ x      b       
     │ Int64  Float64 
─────┼────────────────
   1 │     1     20.2
   2 │     2     30.5
   3 │     3     30.0

In [68]:
filtered_copy = filter(r::DataFrameRow -> r[:x] == 2, df)

1×2 DataFrame
 Row │ x      b       
     │ Int64  Float64 
─────┼────────────────
   1 │     2     30.5

In [69]:
df[1, 1]

1

In [70]:
df[!, 1]

3-element Vector{Int64}:
 1
 2
 3

In [71]:
df[!, :x]

3-element Vector{Int64}:
 1
 2
 3

In [75]:
df[:, Not(:x)]

3×1 DataFrame
 Row │ b       
     │ Float64 
─────┼─────────
   1 │    20.2
   2 │    30.5
   3 │    30.0

In [80]:
df2 = DataFrame(:a => df[!, :x], :x => [5, 4, 3])

3×2 DataFrame
 Row │ a      x     
     │ Int64  Int64 
─────┼──────────────
   1 │     1      5
   2 │     2      4
   3 │     3      3

In [81]:
innerjoin(df2, df, on = :x)

1×3 DataFrame
 Row │ a      x      b       
     │ Int64  Int64  Float64 
─────┼───────────────────────
   1 │     3      3     30.0

In [82]:
show(df, allcols = true)

3×2 DataFrame
 Row │ x      b       
     │ Int64  Float64 
─────┼────────────────
   1 │     1     20.2
   2 │     2     30.5
   3 │     3     30.0