In [1]:
using DataFrames
using Gattino

df = DataFrame("petal" => randn(20), "age" => randn(20), "petal_count" => randn(20), "stem" => randn(20))

[ Info: Precompiling Gattino [f0fb3ee5-f608-41f3-a42d-dac276373afc]


20×4 DataFrame
 Row │ petal       age         petal_count  stem      
     │ Float64     Float64     Float64      Float64   
─────┼────────────────────────────────────────────────
   1 │  0.21737    -2.33314       0.958765   0.176968
   2 │ -2.68126     0.0339573     0.662621   0.874082
   3 │  0.120269    0.237032      0.567466  -0.757848
   4 │  1.80188    -0.849717     -2.66363    0.311951
   5 │ -0.971417    0.331501     -0.371556   1.68966
   6 │ -0.330288    0.970172     -1.13092   -1.23563
   7 │  1.17387    -0.42993      -0.737351  -0.415078
   8 │ -2.10368    -0.108324     -1.72835   -0.1189
   9 │ -0.263264   -2.55568      -0.478376   1.46814
  10 │  0.960648   -0.050765      1.17524    0.315218
  11 │ -1.31969     1.49897      -0.391924  -1.18762
  12 │  0.218067    0.0807973    -0.905891   1.39298
  13 │ -0.420942    0.752357      1.91841   -0.987328
  14 │  0.40084     1.45317       0.207449  -0.189448
  15 │  0.0328708   0.838804      0.194779   1.30539
  16 │  0.403022   -0.345982     -0.157013  -0.286193
  17 │  0.0741845   0.0504081    -0.272236   0.14199
  18 │  0.188804    0.853217      1.42072    0.290749
  19 │ -0.480789    1.09162       0.231601   0.917429
  20 │  0.349262   -0.278074      0.556806  -1.33948

In [2]:
figure1 = scatter(df, "petal", "age", 
title = "flowers", xlabel = "petal", ylabel = "age")

" flowers -2.681 1.4989 -1.560 0.4853 -0.439 -0.528 0.6810 -1.542 1.8018 -2.555 petal age petal_count stem "

" flowers -2.681 1.4989 -1.560 0.4853 -0.439 -0.528 0.6810 -1.542 1.8018 -2.555 petal age petal_count stem "

In [3]:
figure2 = context(250, 250) do con::Context
   Gattino.scatter_plot!(con, df[!, "petal_count"], df[!, "stem"]) 
end

" -2.663 1.6896 -1.518 0.9323 -0.372 0.1750 0.7728 -0.582 1.9184 -1.339 "

" -2.663 1.6896 -1.518 0.9323 -0.372 0.1750 0.7728 -0.582 1.9184 -1.339 "

In [4]:
figure3 = context(500, 500) do con::Context
    group(con) do plotgroup::Group
        group!(plotgroup, "axes") do g::Group
            Gattino.axes!(g)
        end
        group!(plotgroup, "grid") do g::Group
            Gattino.grid!(g, 6)
        end
        group!(plotgroup, "age") do g::Group
            Gattino.points!(g, df[!, "stem"], df[!, "age"], "fill" => "orange")
        end
        group!(plotgroup, "petal") do g::Group
            Gattino.points!(g, df[!, "stem"], df[!, "petal"], "fill" => "lightblue")
        end
    end
end

" "

" "

In [5]:
layers(figure3)

4-element Vector{Pair{Int64, String}}:
 1 => "axes"
 2 => "grid"
 3 => "age"
 4 => "petal"

In [6]:
style!(figure3, "axes", "stroke" => "orange")

In [7]:
open_layer!(figure3, "petal") do ec
    style!(ec, df[!, "petal_count"], "stroke-width" => 5)
    style!(ec, "stroke" => "green")
end

In [8]:
group!(figure3, "annotation") do g::Group
    Gattino.text!(g, 100, 100, "hello !", "stroke" => "darkblue")
end

In [9]:
layers(figure1)

10-element Vector{Pair{Int64, String}}:
  1 => "j9qJSueA"
  2 => "title"
  3 => "axes"
  4 => "grid"
  5 => "age"
  6 => "petal_count"
  7 => "stem"
  8 => "labels"
  9 => "axislabels"
 10 => "legend"

In [10]:
seed_count, stem_count = randn(20), randn(20)

([0.5388265766021577, -1.2228025640379523, 0.451215134033976, 2.1921327059888442, 0.1910924041623354, 1.0299360287436505, 1.200589125974724, -0.589271222972252, 1.0951375392755152, -0.6935366846301898, 0.5102925763883772, -0.012355370796033785, -0.23893759018386676, 0.5150585483637093, -0.9839007032344697, 0.1208508347985274, 2.229629712626705, -0.01600169878807265, -0.11356441727187606, -2.4635065613273017], [1.7703366076442286, -2.0593318220160977, 0.5452310001171969, -2.0216615672348057, -0.4638441389945684, 1.5845438471108468, 0.11331623178655835, 0.6647025054160699, -0.24855677152819133, -0.4757274867095032, -0.7966902946960511, 0.20083394514555375, -0.7818878292073965, -0.527467205935074, 0.8250173320255993, -1.8277821790820272, 0.15495845251732848, 2.1896050531686417, 0.2024469910047206, -1.6946460970088875])

In [11]:
w, h = Int64(round(figure1.dim[1] * .75)), Int64(round(figure1.dim[2] * .75))
ml, mt = Int64(round(figure1.dim[1] * .12)) + figure1.margin[1], Int64(figure1.dim[2] * .12) + figure1.margin[2]

(60, 60)

In [12]:
group(figure1, w, h, ml => mt) do plotgroup::Group
    group!(plotgroup, "seed_count") do g::Group
        Gattino.points!(g, df[!, "petal"], seed_count, "fill" => "brown")
    end
end

In [13]:
layers(figure1)

11-element Vector{Pair{Int64, String}}:
  1 => "j9qJSueA"
  2 => "title"
  3 => "axes"
  4 => "grid"
  5 => "age"
  6 => "petal_count"
  7 => "stem"
  8 => "labels"
  9 => "axislabels"
 10 => "legend"
 11 => "seed_count"

In [14]:
move_layer!(figure1, "seed_count", 8)

11-element Vector{Pair{Int64, String}}:
  1 => "j9qJSueA"
  2 => "title"
  3 => "axes"
  4 => "grid"
  5 => "age"
  6 => "petal_count"
  7 => "stem"
  8 => "seed_count"
  9 => "labels"
 10 => "axislabels"
 11 => "legend"

In [15]:
Gattino.append_legend!(figure1, "seed_count")

In [16]:
open_layer!(figure1, "stem") do ec
    set!(ec, :r, stem_count, max = 10)
end

In [17]:
color = replace(split(figure1["stem"][:children][1]["style"], " ")[2], ";" => "", "'" => "")

rcirc = Gattino.circle("stem_count", r = 2)
style!(rcirc, "fill" => color)
rcirc2 = Gattino.circle("stem_count", r = 4)
style!(rcirc2, "fill" => color)

"'fill: #FF99E6;'"

In [18]:
circgroup = Gattino.ToolipsSVG.g("stem_count")
push!(circgroup, rcirc, rcirc2)

2-element Vector{Vector{Toolips.Servable}}:
 [Toolips.Component{:circle}("stem_count", Dict{Any, Any}(:children => Toolips.Servable[], "style" => "'fill: #FF99E6;'", :r => 2), Toolips.Servable[], "circle"), Toolips.Component{:circle}("stem_count", Dict{Any, Any}(:children => Toolips.Servable[], "style" => "'fill: #FF99E6;'", :r => 4), Toolips.Servable[], "circle")]
 [Toolips.Component{:circle}("stem_count", Dict{Any, Any}(:children => Toolips.Servable[], "style" => "'fill: #FF99E6;'", :r => 2), Toolips.Servable[], "circle"), Toolips.Component{:circle}("stem_count", Dict{Any, Any}(:children => Toolips.Servable[], "style" => "'fill: #FF99E6;'", :r => 4), Toolips.Servable[], "circle")]

In [19]:
Gattino.append_legend!(figure1, "stem_count", circgroup)

In [20]:
figs = hcat(figure2, figure3)

Toolips.Component{:div}("jNb", Dict{Any, Any}(:children => Toolips.Servable[Toolips.Component{:svg}("window", Dict{Any, Any}(:children => Toolips.Servable[Toolips.Component{:g}("axes", Dict{Any, Any}(:children => Toolips.Servable[Toolips.Component{:line}("CTCJfmdZ", Dict{Any, Any}(:children => Toolips.Servable[], :y1 => 250, :x2 => 250, "style" => "'fill: none;stroke: black;stroke-width: 4;'", :y2 => 250, :x1 => 0), Toolips.Servable[], "line"), Toolips.Component{:line}("NC7lfEmx", Dict{Any, Any}(:children => Toolips.Servable[], :y1 => 0, :x2 => 0, "style" => "'fill: none;stroke: black;stroke-width: 4;'", :y2 => 250, :x1 => 0), Toolips.Servable[], "line")], :height => 250, :width => 250), Toolips.Servable[], "g"), Toolips.Component{:g}("grid", Dict{Any, Any}(:children => Toolips.Servable[Toolips.Component{:line}("QSq4HnEt", Dict{Any, Any}(:children => Toolips.Servable[], :y1 => 0, :x2 => 1, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 250, :x1 => 1), Toolips.Servable[], "line"), Toolips.Component{:line}("TRwKoYwT", Dict{Any, Any}(:children => Toolips.Servable[], :y1 => 1, :x2 => 250, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 1, :x1 => 0), Toolips.Servable[], "line"), Toolips.Component{:line}("xzoyZ5MS", Dict{Any, Any}(:children => Toolips.Servable[], :y1 => 0, :x2 => 63, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 250, :x1 => 63), Toolips.Servable[], "line"), Toolips.Component{:line}("UFiAOmPM", Dict{Any, Any}(:children => Toolips.Servable[], :y1 => 63, :x2 => 250, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 63, :x1 => 0), Toolips.Servable[], "line"), Toolips.Component{:line}("FeoDCZeb", Dict{Any, Any}(:children => Toolips.Servable[], :y1 => 0, :x2 => 125, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 250, :x1 => 125), Toolips.Servable[], "line"), Toolips.Component{:line}("56kSGulB", Dict{Any, Any}(:children => Toolips.Servable[], :y1 => 125, :x2 => 250, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 125, :x1 => 0), Toolips.Servable[], "line"), Toolips.Component{:line}("RVWWAeGJ", Dict{Any, Any}(:children => Toolips.Servable[], :y1 => 0, :x2 => 187, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 250, :x1 => 187), Toolips.Servable[], "line"), Toolips.Component{:line}("vxnrZAks", Dict{Any, Any}(:children => Toolips.Servable[], :y1 => 187, :x2 => 250, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 187, :x1 => 0), Toolips.Servable[], "line"), Toolips.Component{:line}("6hKJpDEV", Dict{Any, Any}(:children => Toolips.Servable[], :y1 => 0, :x2 => 249, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 250, :x1 => 249), Toolips.Servable[], "line"), Toolips.Component{:line}("87j3i1Hd", Dict{Any, Any}(:children => Toolips.Servable[], :y1 => 249, :x2 => 250, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 249, :x1 => 0), Toolips.Servable[], "line")], :height => 250, :width => 250), Toolips.Servable[], "g"), Toolips.Component{:g}("points", Dict{Any, Any}(:children => Toolips.Servable[Toolips.Component{:circle}("rmogxlj1", Dict{Any, Any}(:children => Toolips.Servable[], :cx => 197, "style" => "'fill: #FF6633;'", :r => 5, :cy => 125), Toolips.Servable[], "circle"), Toolips.Component{:circle}("WNM1IENw", Dict{Any, Any}(:children => Toolips.Servable[], :cx => 181, "style" => "'fill: #FF6633;'", :r => 5, :cy => 68), Toolips.Servable[], "circle"), Toolips.Component{:circle}("eMS6JW6a", Dict{Any, Any}(:children => Toolips.Servable[], :cx => 176, "style" => "'fill: #FF6633;'", :r => 5, :cy => 202), Toolips.Servable[], "circle"), Toolips.Component{:circle}("URIiYbgk", Dict{Any, Any}(:children => Toolips.Servable[], :cx => 0, "style" => "'fill: #FF6633;'", :r => 5, :cy => 114), Toolips.Servable[], 

In [21]:
plt = context(200, 200) do con::Context
    group!(con, "points") do g::Group
        Gattino.points!(g, [5, 10, 15], [5, 10, 15])
    end
end
plt2 = context(200, 200) do con::Context
    group!(con, "points") do g::Group
        Gattino.points!(g, [5, 10, 15], [5, 10, 15], "fill" => "blue")
    end
end
n = compose("new", plt2, plt)

Toolips.Component{:div}("new", Dict{Any, Any}(:children => Toolips.Servable[Toolips.Component{:svg}("window", Dict{Any, Any}(:children => Toolips.Servable[Toolips.Component{:g}("points", Dict{Any, Any}(:children => Toolips.Servable[Toolips.Component{:circle}("VzpwUko3", Dict{Any, Any}(:children => Toolips.Servable[], :cx => 0, "style" => "'fill: blue;'", :r => 5, :cy => 200), Toolips.Servable[], "circle"), Toolips.Component{:circle}("NUj6V5bp", Dict{Any, Any}(:children => Toolips.Servable[], :cx => 100, "style" => "'fill: blue;'", :r => 5, :cy => 100), Toolips.Servable[], "circle"), Toolips.Component{:circle}("Wzzn7B7m", Dict{Any, Any}(:children => Toolips.Servable[], :cx => 199, "style" => "'fill: blue;'", :r => 5, :cy => 1), Toolips.Servable[], "circle")], :height => 200, :width => 200), Toolips.Servable[], "g")], :height => 200, "style" => "'display: inline-block;'", :width => 200), Toolips.Servable[], "svg"), Toolips.Component{:svg}("window", Dict{Any, Any}(:children => Toolips.Servable[Toolips.Component{:g}("points", Dict{Any, Any}(:children => Toolips.Servable[Toolips.Component{:circle}("bJcXdcSs", Dict{Any, Any}(:children => Toolips.Servable[], :cx => 0, "style" => "'fill: orange;stroke: lightblue;stroke-width: 0;'", :r => 5, :cy => 200), Toolips.Servable[], "circle"), Toolips.Component{:circle}("cL4FuIru", Dict{Any, Any}(:children => Toolips.Servable[], :cx => 100, "style" => "'fill: orange;stroke: lightblue;stroke-width: 0;'", :r => 5, :cy => 100), Toolips.Servable[], "circle"), Toolips.Component{:circle}("9ZRoCPux", Dict{Any, Any}(:children => Toolips.Servable[], :cx => 199, "style" => "'fill: orange;stroke: lightblue;stroke-width: 0;'", :r => 5, :cy => 1), Toolips.Servable[], "circle")], :height => 200, :width => 200), Toolips.Servable[], "g")], :height => 200, "style" => "'display: inline-block;'", :width => 200), Toolips.Servable[], "svg")]), Toolips.Servable[], "div")

In [22]:
gridboxes = context(500, 500) do con::Context
   
end

" "

" "

In [23]:
gridboxes = context(500, 500) do con::Context
    group(con, 250, 250) do g::Group
        Gattino.grid!(g, 6)
    end
end

" "

" "

In [24]:
gridboxes = context(500, 500) do con::Context
    group(con, 250, 250) do g::Group
        Gattino.grid!(g, 6, "stroke" => "darkred")
    end
    group(con, 250, 250, 250 => 0) do g::Group
        Gattino.grid!(g, 6, "stroke" => "darkgreen")
    end
    group(con, 250, 250, 0 => 250) do g::Group
        Gattino.grid!(g, 6, "stroke" => "purple")
    end
    group(con, 250, 250, 250 => 250) do g::Group
        Gattino.grid!(g, 6, "stroke" => "darkblue")
    end
end

" "

" "

In [25]:
layers(figure3)

5-element Vector{Pair{Int64, String}}:
 1 => "axes"
 2 => "grid"
 3 => "age"
 4 => "petal"
 5 => "annotation"

In [26]:
reshape(figure3, "age", :star)

20-element Vector{Toolips.Component{:star}}:
 Toolips.Component{:star}("6Kk0buCk", Dict{Any, Any}(:np => 5, "points" => "'260.0 478.0,257.42705098312484 479.76335575687744,256.54508497187476 482.75528258147574,254.07294901687516 480.8531695488855,250.95491502812527 480.93892626146237,252.0 478.0,250.95491502812527 475.06107373853763,254.07294901687516 475.14683045111457,256.54508497187476 473.24471741852426,257.42705098312484 476.23664424312256,260.0 478.0'", :ir => 3, :children => Toolips.Servable[], :y => 478, :angle => 0.6283185307179586, :r => 5, :x => 255), Toolips.Servable[], "polygon")
 Toolips.Component{:star}("7agbVkqe", Dict{Any, Any}(:np => 5, "points" => "'375.0 186.0,372.42705098312484 187.76335575687742,371.54508497187476 190.75528258147577,369.07294901687516 188.85316954888546,365.95491502812524 188.93892626146237,367.0 186.0,365.95491502812524 183.06107373853763,369.07294901687516 183.14683045111454,371.54508497187476 181.24471741852423,372.42705098312484 184.2366442431

In [27]:
style!(figure3, "age", "fill" => "orange", "stroke" => "black", "stroke-width" => 2px)

In [28]:
Gattino.legend!(figure3, ["age"])

circpreview = Gattino.circle("radiusprev", r = 3)
style!(circpreview, "stroke" => "darkgreen", "stroke-width" => 2px, "fill" => "white")

Gattino.append_legend!(figure3, "petal count", circpreview)

In [29]:
myanim = Animation("fadein", iterations = 1, length = 1.1)

Animation("fadein", Dict{Any, Any}(), Toolips.Servable[], Toolips.var"#f#122"{String}("fadein", Core.Box(Dict{Any, Any}())), 0.0, 1.1, 1)

In [30]:
Gattino.animate!(figure3, "age", myanim)

2-element Vector{Toolips.Servable}:
 Toolips.Style(".fadein-style", Dict{Any, Any}("animation-name" => "fadein", "animation-duration" => "1.1s", "animation-iteration-count" => "1"), Toolips.Servable[Animation("fadein", Dict{Any, Any}(), Toolips.Servable[], Toolips.var"#f#122"{String}("fadein", Core.Box(Dict{Any, Any}())), 0.0, 1.1, 1)])
 Animation("fadein", Dict{Any, Any}(), Toolips.Servable[], Toolips.var"#f#122"{String}("fadein", Core.Box(Dict{Any, Any}())), 0.0, 1.1, 1)

In [31]:
using Gattino.Toolips

main = route("/") do c::Connection
    bod = body("mainbody", align = "center")
    visheader = Toolips.h("heading", 2, text = "my gattino visualization")
    style!(visheader, "color" => "purple")
    push!(bod, visheader, figure1.window)
    write!(c, bod)
end

ws = WebServer(routes = [main])

ws.start()

[ Info: Listening on: 127.0.0.1:8000, thread id: 1


In [32]:
using GattinoInteractive

[ Info: Precompiling GattinoInteractive [4120b9a3-2441-4f88-b64c-abd29fac8134]


In [33]:
figure2

" -2.663 1.6896 -1.518 0.9323 -0.372 0.1750 0.7728 -0.582 1.9184 -1.339 "

" -2.663 1.6896 -1.518 0.9323 -0.372 0.1750 0.7728 -0.582 1.9184 -1.339 "

In [47]:
newvis = scatter(randn(20), randn(20))
style!(newvis, "points", "transition" => 10seconds)
newcontrols = controls(500, 500) do con::Controls
    changebutt = button("changebutt", text = "change")
    bind!(newvis, changebutt) do pm::PlotModifier{Context}
        GattinoInteractive.style_layer!(pm, "points", "opacity" => 0percent)
    end
    push!(con.window, changebutt)
end
nothing

In [48]:
hcat(newvis, newcontrols)

Component{:div}("eqj", Dict{Any, Any}(:children => Servable[Component{:svg}("window", Dict{Any, Any}(:children => Servable[Component{:g}("axes", Dict{Any, Any}(:children => Servable[Component{:line}("Es06FqV9", Dict{Any, Any}(:children => Servable[], :y1 => 500, :x2 => 500, "style" => "'fill: none;stroke: black;stroke-width: 4;'", :y2 => 500, :x1 => 0), Servable[], "line"), Component{:line}("tWS4KVy3", Dict{Any, Any}(:children => Servable[], :y1 => 0, :x2 => 0, "style" => "'fill: none;stroke: black;stroke-width: 4;'", :y2 => 500, :x1 => 0), Servable[], "line")], :height => 500, :width => 500), Servable[], "g"), Component{:g}("grid", Dict{Any, Any}(:children => Servable[Component{:line}("Kf4qTNsS", Dict{Any, Any}(:children => Servable[], :y1 => 0, :x2 => 1, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 500, :x1 => 1), Servable[], "line"), Component{:line}("8nww8yKZ", Dict{Any, Any}(:children => Servable[], :y1 => 1, :x2 => 500, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 1, :x1 => 0), Servable[], "line"), Component{:line}("b9EZGNKs", Dict{Any, Any}(:children => Servable[], :y1 => 0, :x2 => 126, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 500, :x1 => 126), Servable[], "line"), Component{:line}("tqhDmq6A", Dict{Any, Any}(:children => Servable[], :y1 => 126, :x2 => 500, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 126, :x1 => 0), Servable[], "line"), Component{:line}("N4x22Mj8", Dict{Any, Any}(:children => Servable[], :y1 => 0, :x2 => 251, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 500, :x1 => 251), Servable[], "line"), Component{:line}("uZ2LagW9", Dict{Any, Any}(:children => Servable[], :y1 => 251, :x2 => 500, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 251, :x1 => 0), Servable[], "line"), Component{:line}("GwgjRKoE", Dict{Any, Any}(:children => Servable[], :y1 => 0, :x2 => 376, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 500, :x1 => 376), Servable[], "line"), Component{:line}("ogfQfhNR", Dict{Any, Any}(:children => Servable[], :y1 => 376, :x2 => 500, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 376, :x1 => 0), Servable[], "line")], :height => 500, :width => 500), Servable[], "g"), Component{:g}("points", Dict{Any, Any}(:children => Servable[Component{:circle}("39eTlQS1", Dict{Any, Any}(:children => Servable[], :cx => 227, "style" => "'fill: #FF6633;transition: 10s;'", :r => 5, :cy => 232), Servable[], "circle"), Component{:circle}("IHY8EmAV", Dict{Any, Any}(:children => Servable[], :cx => 201, "style" => "'fill: #FF6633;transition: 10s;'", :r => 5, :cy => 222), Servable[], "circle"), Component{:circle}("UQlRO9Of", Dict{Any, Any}(:children => Servable[], :cx => 209, "style" => "'fill: #FF6633;transition: 10s;'", :r => 5, :cy => 385), Servable[], "circle"), Component{:circle}("J6vaCVYV", Dict{Any, Any}(:children => Servable[], :cx => 312, "style" => "'fill: #FF6633;transition: 10s;'", :r => 5, :cy => 500), Servable[], "circle"), Component{:circle}("OmBH5ZoZ", Dict{Any, Any}(:children => Servable[], :cx => 208, "style" => "'fill: #FF6633;transition: 10s;'", :r => 5, :cy => 124), Servable[], "circle"), Component{:circle}("kHdJ1UdE", Dict{Any, Any}(:children => Servable[], :cx => 168, "style" => "'fill: #FF6633;transition: 10s;'", :r => 5, :cy => 421), Servable[], "circle"), Component{:circle}("ZoSy1WYP", Dict{Any, Any}(:children => Servable[], :cx => 330, "style" => "'fill: #FF6633;transition: 10s;'", :r => 5, :cy => 408), Servable[], "circle"), Component{:circle}("HtZ5eEME", Dict{Any, Any}(:children => Servable[], :cx => 192, "style" => "'fill: #FF6633;transition: 10s;'", :r => 5, :cy => 284), Servable[], "circle"), Component{:circle}("kkXu4Am9", Dict{Any, Any}(:children => Servable[], :cx => 35, "style" => "'fill: #FF6633;transition: 1

In [50]:
flowers = Dict(:color => ["orange", "red", "white", "orange", "red", "pink"], 
               :petal => [10, 4, 7, 9, 5, 7], :stem => [20, 14, 16, 6, 9, 5], 
               :score => [4, 2, 6, 8, 10, 3], :n_petals => [4, 9, 4, 12, 8, 4], 
               :name => ["daisy", "rose", "lilac", "poppy", "cherry"])

Dict{Symbol, Vector} with 6 entries:
  :color    => ["orange", "red", "white", "orange", "red", "pink"]
  :n_petals => [4, 9, 4, 12, 8, 4]
  :petal    => [10, 4, 7, 9, 5, 7]
  :name     => ["daisy", "rose", "lilac", "poppy", "cherry"]
  :score    => [4, 2, 6, 8, 10, 3]
  :stem     => [20, 14, 16, 6, 9, 5]

In [51]:
plt = context(500, 500) do con::Context
    Gattino.scatter_plot!(con, flowers[:score], flowers[:n_petals])
    open_layer!(con, "points") do ecomp
        set!(ecomp, :r, flowers[:petal])
        style!(ecomp, "fill", flowers[:color])
        style!(ecomp[2], "transition" => 1seconds)
    end
    style!(con, "border-top-left-radius" => 8px, "border-bottom-left-radius" => 8px,
    "border" => "2px solid black", "border-right" => "1px solid gray")
end
ctrls = controls(500, 500) do ct::Controls
    fetsel = Gattino.h("selectcat", 2, text = "show feature")
    style!(fetsel, "color" => "purple", "margin-bottom" => 8px)
    push!(ct, fetsel)
    opts = options("n_petals", "stem", "petal")
    selectfeatbox = selection_box("featb", opts)
    style!(selectfeatbox, "height" => 5percent, "color" => "gray", "font-size" => 13pt, "margin-left" => 30px)
    bind!(plt, selectfeatbox) do gm::PlotModifier
         value_is!(gm, selectfeatbox, "stem") do gm2::PlotModifier
             Gattino.points!(gm2, "points", flowers[:score], flowers[:stem])
         end
         value_is!(gm, selectfeatbox, "petal") do gm2::PlotModifier
             Gattino.points!(gm2, "points", flowers[:score], flowers[:petal])
         end
         value_is!(gm, selectfeatbox, "n_petals") do gm2::PlotModifier
             Gattino.points!(gm2, "points", flowers[:score], flowers[:n_petals])
         end
    end
    push!(ct, selectfeatbox)
    style!(ct, "border-top-left-radius" => 0px, "border-bottom-left-radius" => 0px, "border" => "2px solid black", "border-left" => "none",
    "padding" => 20px)
end
compose("flowervis", plt, ctrls)

Component{:div}("flowervis", Dict{Any, Any}(:children => Servable[Component{:svg}("window", Dict{Any, Any}(:children => Servable[Component{:g}("axes", Dict{Any, Any}(:children => Servable[Component{:line}("wfyFlSNS", Dict{Any, Any}(:children => Servable[], :y1 => 500, :x2 => 500, "style" => "'fill: none;stroke: black;stroke-width: 4;'", :y2 => 500, :x1 => 0), Servable[], "line"), Component{:line}("iCh8t5cL", Dict{Any, Any}(:children => Servable[], :y1 => 0, :x2 => 0, "style" => "'fill: none;stroke: black;stroke-width: 4;'", :y2 => 500, :x1 => 0), Servable[], "line")], :height => 500, :width => 500), Servable[], "g"), Component{:g}("grid", Dict{Any, Any}(:children => Servable[Component{:line}("5lcBqQp8", Dict{Any, Any}(:children => Servable[], :y1 => 0, :x2 => 1, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 500, :x1 => 1), Servable[], "line"), Component{:line}("yitdtiKa", Dict{Any, Any}(:children => Servable[], :y1 => 1, :x2 => 500, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 1, :x1 => 0), Servable[], "line"), Component{:line}("Zpqw2kFM", Dict{Any, Any}(:children => Servable[], :y1 => 0, :x2 => 126, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 500, :x1 => 126), Servable[], "line"), Component{:line}("KFF2Vsos", Dict{Any, Any}(:children => Servable[], :y1 => 126, :x2 => 500, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 126, :x1 => 0), Servable[], "line"), Component{:line}("SOlN8S3u", Dict{Any, Any}(:children => Servable[], :y1 => 0, :x2 => 251, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 500, :x1 => 251), Servable[], "line"), Component{:line}("MJIecE0A", Dict{Any, Any}(:children => Servable[], :y1 => 251, :x2 => 500, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 251, :x1 => 0), Servable[], "line"), Component{:line}("E8a9qzih", Dict{Any, Any}(:children => Servable[], :y1 => 0, :x2 => 376, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 500, :x1 => 376), Servable[], "line"), Component{:line}("Rj1OygbB", Dict{Any, Any}(:children => Servable[], :y1 => 376, :x2 => 500, "style" => "'fill: none;stroke: lightblue;stroke-width: 1;opacity: 80%;'", :y2 => 376, :x1 => 0), Servable[], "line")], :height => 500, :width => 500), Servable[], "g"), Component{:g}("points", Dict{Any, Any}(:children => Servable[Component{:circle}("56LT9oEE", Dict{Any, Any}(:children => Servable[], :cx => 125, "style" => "'fill: #FF6633;fill: orange;transition: 1s;'", :r => 10, :cy => 500), Servable[], "circle"), Component{:circle}("YuBZquHN", Dict{Any, Any}(:children => Servable[], :cx => 0, "style" => "'fill: #FF6633;fill: red;transition: 1s;'", :r => 4, :cy => 188), Servable[], "circle"), Component{:circle}("nyRnwSBH", Dict{Any, Any}(:children => Servable[], :cx => 250, "style" => "'fill: #FF6633;fill: white;transition: 1s;'", :r => 7, :cy => 500), Servable[], "circle"), Component{:circle}("OUnTZ5Mw", Dict{Any, Any}(:children => Servable[], :cx => 374, "style" => "'fill: #FF6633;fill: orange;transition: 1s;'", :r => 9, :cy => 1), Servable[], "circle"), Component{:circle}("wM5Oqv70", Dict{Any, Any}(:children => Servable[], :cx => 499, "style" => "'fill: #FF6633;fill: red;transition: 1s;'", :r => 5, :cy => 250), Servable[], "circle"), Component{:circle}("dN4dtCxn", Dict{Any, Any}(:children => Servable[], :cx => 62, "style" => "'fill: #FF6633;fill: pink;transition: 1s;'", :r => 7, :cy => 500), Servable[], "circle")], :height => 500, :width => 500), Servable[], "g"), Component{:g}("labels", Dict{Any, Any}(:children => Servable[Component{:text}("0ao7TtO7", Dict{Any, Any}(:children => Servable[], :y => 490, "style" => "'fill: black;font-size: 10pt;'", :text => "2", :x => 2), Servable[], "text"), Component{:text}("Fi11MjgZ", Dict{Any, Any}(:children => Servable[], :y => 4, "style" => "'fill: black;font-size: 10pt;'", :t

In [36]:
using Gattino3D

[ Info: Precompiling Gattino3D [a217f6c4-9a08-4218-8fae-34c5d6be422b]


In [37]:
mycon = Gattino3D.context(500, 500, 200) do con
    Gattino3D.axes!(con)
    Gattino3D.grid!(con, 6)
    Gattino3D.points!(con, [1, 5, 10], [1, 5, 10], [1, 5, 10])
    Gattino3D.points!(con, Vector(1:10), [1, 1, 1, 1, 1, 1, 1, 1, 1, 10], [3, 1, 3, 1, 6, 1, 3, 1, 2, 10], 
    "fill" => "blue")
    Gattino3D.line!(con, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 10], [0, 1, 0, 1, 0, 1, 0, 1, 0, 10], "stroke" => "green", "fill" => "none", 
"stroke-width" => 10px)
end

" "

" "