In [4]:
one_D = [5, 5, 7, 2, 3]

5-element Vector{Int64}:
 5
 5
 7
 2
 3

In [5]:
one_D2 = [9 , 10, 3, 0, 1]

5-element Vector{Int64}:
  9
 10
  3
  0
  1

In [6]:
multi_D = [5 10 2 4; 5 8 10 3]

2×4 Matrix{Int64}:
 5  10   2  4
 5   8  10  3

In [7]:
multi_D2 = [10 7 4 3; 9 5 3 10]

2×4 Matrix{Int64}:
 10  7  4   3
  9  5  3  10

In [16]:
println("An array is a sub-type of an abstract array:\n")
println("Type: ", typeof(one_D))
println(typeof(one_D2) <: AbstractArray)
println("\n==============================\n")
println("Is a matrix an abstract array?\n")
println("Type: ", typeof(multi_D2))
println(typeof(multi_D) <: AbstractArray)

An array is a sub-type of an abstract array:

Type: Vector{Int64}
true


Is a matrix an abstract array?

Type: Matrix{Int64}
true


In [17]:
println(length(multi_D))

8


In [7]:
size(one_D)

(5,)

In [8]:
size(multi_D)

(2, 4)

In [34]:
copmd = copy(multi_D)

2×4 Matrix{Int64}:
 5  10   2  4
 5   8  10  3

In [35]:
size(copmd)

(2, 4)

In [39]:
copmd = reshape(copmd, (4, 2))

4×2 Matrix{Int64}:
  5   2
  5  10
 10   4
  8   3

In [40]:
copmd

4×2 Matrix{Int64}:
  5   2
  5  10
 10   4
  8   3

In [48]:
println("We went from this")
display(multi_D)

2×4 Matrix{Int64}:
 5  10   2  4
 5   8  10  3

We went from this


In [47]:
println("to this:")
display(copmd)

4×2 Matrix{Int64}:
  5   2
  5  10
 10   4
  8   3

to this:


In [51]:
zeros((5, 10))

5×10 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [57]:
using LinearAlgebra

In [60]:
multi_D

2×4 Matrix{Int64}:
 5  10   2  4
 5   8  10  3

In [63]:
5I

UniformScaling{Int64}
5*I

In [49]:
transpose(multi_D)

4×2 transpose(::Matrix{Int64}) with eltype Int64:
  5   5
 10   8
  2  10
  4   3

In [67]:
multi_D .* multi_D2

2×4 Matrix{Int64}:
 50  70   8  12
 45  40  30  30

In [68]:
multi_D .+ multi_D2

2×4 Matrix{Int64}:
 15  17   6   7
 14  13  13  13

In [69]:
multi_D .- multi_D2

2×4 Matrix{Int64}:
 -5  3  -2   1
 -4  3   7  -7

In [70]:
multi_D ./ multi_D2

2×4 Matrix{Float64}:
 0.5       1.42857  0.5      1.33333
 0.555556  1.6      3.33333  0.3

In [71]:
one_D .* one_D2

5-element Vector{Int64}:
 45
 50
 21
  0
  3

In [72]:
dot(multi_D, multi_D2)

285

In [76]:
hcat(multi_D, multi_D2)

2×8 Matrix{Int64}:
 5  10   2  4  10  7  4   3
 5   8  10  3   9  5  3  10

In [81]:
cumsum(multi_D, dims = 5)

2×4 Matrix{Int64}:
 5  10   2  4
 5   8  10  3