In [6]:
Main

Main

In [7]:
xz = 5

5

In [8]:
Main.xz

5

In [1]:
@doc readdir

```
readdir(dir::AbstractString=pwd();
    join::Bool = false,
    sort::Bool = true,
) -> Vector{String}
```

Return the names in the directory `dir` or the current working directory if not given. When `join` is false, `readdir` returns just the names in the directory as is; when `join` is true, it returns `joinpath(dir, name)` for each `name` so that the returned strings are full paths. If you want to get absolute paths back, call `readdir` with an absolute directory path and `join` set to true.

By default, `readdir` sorts the list of names it returns. If you want to skip sorting the names and get them in the order that the file system lists them, you can use `readdir(dir, sort=false)` to opt out of sorting.

See also: [`walkdir`](@ref).

!!! compat "Julia 1.4"
    The `join` and `sort` keyword arguments require at least Julia 1.4.


# Examples

```julia-repl
julia> cd("/home/JuliaUser/dev/julia")

julia> readdir()
30-element Array{String,1}:
 ".appveyor.yml"
 ".git"
 ".gitattributes"
 ⋮
 "ui"
 "usr"
 "usr-staging"

julia> readdir(join=true)
30-element Array{String,1}:
 "/home/JuliaUser/dev/julia/.appveyor.yml"
 "/home/JuliaUser/dev/julia/.git"
 "/home/JuliaUser/dev/julia/.gitattributes"
 ⋮
 "/home/JuliaUser/dev/julia/ui"
 "/home/JuliaUser/dev/julia/usr"
 "/home/JuliaUser/dev/julia/usr-staging"

julia> readdir("base")
145-element Array{String,1}:
 ".gitignore"
 "Base.jl"
 "Enums.jl"
 ⋮
 "version_git.sh"
 "views.jl"
 "weakkeydict.jl"

julia> readdir("base", join=true)
145-element Array{String,1}:
 "base/.gitignore"
 "base/Base.jl"
 "base/Enums.jl"
 ⋮
 "base/version_git.sh"
 "base/views.jl"
 "base/weakkeydict.jl"```

julia> readdir(abspath("base"), join=true)
145-element Array{String,1}:
 "/home/JuliaUser/dev/julia/base/.gitignore"
 "/home/JuliaUser/dev/julia/base/Base.jl"
 "/home/JuliaUser/dev/julia/base/Enums.jl"
 ⋮
 "/home/JuliaUser/dev/julia/base/version_git.sh"
 "/home/JuliaUser/dev/julia/base/views.jl"
 "/home/JuliaUser/dev/julia/base/weakkeydict.jl"
```


In [2]:
readdoc = @doc readdir

```
readdir(dir::AbstractString=pwd();
    join::Bool = false,
    sort::Bool = true,
) -> Vector{String}
```

Return the names in the directory `dir` or the current working directory if not given. When `join` is false, `readdir` returns just the names in the directory as is; when `join` is true, it returns `joinpath(dir, name)` for each `name` so that the returned strings are full paths. If you want to get absolute paths back, call `readdir` with an absolute directory path and `join` set to true.

By default, `readdir` sorts the list of names it returns. If you want to skip sorting the names and get them in the order that the file system lists them, you can use `readdir(dir, sort=false)` to opt out of sorting.

See also: [`walkdir`](@ref).

!!! compat "Julia 1.4"
    The `join` and `sort` keyword arguments require at least Julia 1.4.


# Examples

```julia-repl
julia> cd("/home/JuliaUser/dev/julia")

julia> readdir()
30-element Array{String,1}:
 ".appveyor.yml"
 ".git"
 ".gitattributes"
 ⋮
 "ui"
 "usr"
 "usr-staging"

julia> readdir(join=true)
30-element Array{String,1}:
 "/home/JuliaUser/dev/julia/.appveyor.yml"
 "/home/JuliaUser/dev/julia/.git"
 "/home/JuliaUser/dev/julia/.gitattributes"
 ⋮
 "/home/JuliaUser/dev/julia/ui"
 "/home/JuliaUser/dev/julia/usr"
 "/home/JuliaUser/dev/julia/usr-staging"

julia> readdir("base")
145-element Array{String,1}:
 ".gitignore"
 "Base.jl"
 "Enums.jl"
 ⋮
 "version_git.sh"
 "views.jl"
 "weakkeydict.jl"

julia> readdir("base", join=true)
145-element Array{String,1}:
 "base/.gitignore"
 "base/Base.jl"
 "base/Enums.jl"
 ⋮
 "base/version_git.sh"
 "base/views.jl"
 "base/weakkeydict.jl"```

julia> readdir(abspath("base"), join=true)
145-element Array{String,1}:
 "/home/JuliaUser/dev/julia/base/.gitignore"
 "/home/JuliaUser/dev/julia/base/Base.jl"
 "/home/JuliaUser/dev/julia/base/Enums.jl"
 ⋮
 "/home/JuliaUser/dev/julia/base/version_git.sh"
 "/home/JuliaUser/dev/julia/base/views.jl"
 "/home/JuliaUser/dev/julia/base/weakkeydict.jl"
```


In [5]:
print(typeof(readdoc))

Markdown.MD

In [9]:
string(readdoc)

"```\nreaddir(dir::AbstractString=pwd();\n    join::Bool = false,\n    sort::Bool = true,\n) -> Vector{String}\n```\n\nReturn the names in the directory `dir` or the current working directory if not given. When `join` is false, `readdir` returns just the names in the directory " ⋯ 1464 bytes ⋯ "JuliaUser/dev/julia/base/.gitignore\"\n \"/home/JuliaUser/dev/julia/base/Base.jl\"\n \"/home/JuliaUser/dev/julia/base/Enums.jl\"\n ⋮\n \"/home/JuliaUser/dev/julia/base/version_git.sh\"\n \"/home/JuliaUser/dev/julia/base/views.jl\"\n \"/home/JuliaUser/dev/julia/base/weakkeydict.jl\"\n```\n"

In [15]:
struct Constructor
    x::Int64
    y::Float64
end

In [16]:
fieldnames(Constructor)

(:x, :y)

In [12]:
roundit(x::Int64) = x
roundit(x::Float64) = Int64(round(x))

roundit (generic function with 2 methods)

In [17]:
rit_methods = methods(roundit)

# 2 methods for generic function "roundit" from Main:
 [1] roundit(x::Int64)
     @ In[12]:1
 [2] roundit(x::Float64)
     @ In[12]:2

In [18]:
rit_methods[1].sig

Tuple{typeof(roundit), Int64}

In [19]:
Base.delete_method(rit_methods[1])

In [21]:
methods(roundit)

# 1 method for generic function "roundit" from Main:
 [1] roundit(x::Float64)
     @ In[12]:2

In [22]:
names(Main)

8-element Vector{Symbol}:
 :Base
 :Constructor
 :Core
 :Main
 :readdoc
 :rit_methods
 :roundit
 :xz

In [23]:
myd = Dict(:A => "B", :C => "D")

Dict{Symbol, String} with 2 entries:
  :A => "B"
  :C => "D"

In [24]:
delete!(myd, :A)

Dict{Symbol, String} with 1 entry:
  :C => "D"

In [25]:
x = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [26]:
deleteat!(x, 2)

2-element Vector{Int64}:
 1
 3

In [27]:
myt = Constructor(5, 5.5)

Constructor(5, 5.5)

In [28]:
typeof(myt)

Constructor

In [30]:
@code_llvm roundit(5.5)

;  @ In[12]:2 within `roundit`
define i64 @julia_roundit_2575(double %0) #0 {
top:
  %gcframe10 = alloca [6 x {}*], align 16
  %gcframe10.sub = getelementptr inbounds [6 x {}*], [6 x {}*]* %gcframe10, i64 0, i64 0
  %1 = bitcast [6 x {}*]* %gcframe10 to i8*
  call void @llvm.memset.p0i8.i32(i8* noundef nonnull align 16 dereferenceable(48) %1, i8 0, i32 48, i1 false)
  %2 = getelementptr inbounds [6 x {}*], [6 x {}*]* %gcframe10, i64 0, i64 2
  %thread_ptr = call i8* asm "movq %fs:0, $0", "=r"() #6
  %ppgcstack_i8 = getelementptr i8, i8* %thread_ptr, i64 -8
  %ppgcstack = bitcast i8* %ppgcstack_i8 to {}****
  %pgcstack = load {}***, {}**** %ppgcstack, align 8
; ┌ @ floatfuncs.jl:128 within `round` @ float.jl:395
   %3 = bitcast [6 x {}*]* %gcframe10 to i64*
   store i64 16, i64* %3, align 16
   %4 = getelementptr inbounds [6 x {}*], [6 x {}*]* %gcframe10, i64 0, i64 1
   %5 = bitcast {}** %4 to {}***
   %6 = load {}**, {}*** %pgcstack, align 8
   store {}** %6, {}*** %5, align 8
   %7 =