In [21]:
# If your installation worked out correctly, this should run:
using Lathe

┌ Info: Precompiling Lathe [38d8eb38-e7b1-11e9-0012-376b6c802672]
└ @ Base loading.jl:1278


=== Lathe 0.1.2 Butterball ===
-0-0- Easily ML -0-0-
Thank you for trying Lathe!
-0-0- Contributors -0-0-
emmettgbstefanches7PallHaraldson


In [22]:
?(Lathe)

search: Lathe JULIA_NUM_THREADS relpath realpath splitpath LOAD_PATH



|====== Lathe - Easily ML =====

|= = = = = v. 0.1.2 = = = = = |

|==============================

|__________Lathe.stats

|__________Lathe.preprocess

|__________Lathe.models

|______________________________

Use ?(Lathe.package) for information!

[uuid]

38d8eb38-e7b1-11e9-0012-376b6c802672

[deps]

DataFrames.jl

Random.jl

```

```


In [23]:
using Lathe: stats

In [24]:
?(stats)

search: startswith AbstractSet AbstractString ignorestatus MathConstants



BoundsError: BoundsError: attempt to access 0-element Array{SubString{String},1} at index [1]

In [25]:
using CSV

In [26]:
df = CSV.read("car data.csv")

301×9 DataFrame. Omitted printing of 4 columns
│ Row │ Car_Name      │ Year  │ Selling_Price │ Present_Price │ Kms_Driven │
│     │ String        │ Int64 │ Float64       │ Float64       │ Int64      │
├─────┼───────────────┼───────┼───────────────┼───────────────┼────────────┤
│ 1   │ ritz          │ 2014  │ 3.35          │ 5.59          │ 27000      │
│ 2   │ sx4           │ 2013  │ 4.75          │ 9.54          │ 43000      │
│ 3   │ ciaz          │ 2017  │ 7.25          │ 9.85          │ 6900       │
│ 4   │ wagon r       │ 2011  │ 2.85          │ 4.15          │ 5200       │
│ 5   │ swift         │ 2014  │ 4.6           │ 6.87          │ 42450      │
│ 6   │ vitara brezza │ 2018  │ 9.25          │ 9.83          │ 2071       │
│ 7   │ ciaz          │ 2015  │ 6.75          │ 8.12          │ 18796      │
│ 8   │ s cross       │ 2015  │ 6.5           │ 8.61          │ 33429      │
│ 9   │ ciaz          │ 2016  │ 8.75          │ 8.89          │ 20273      │
│ 10  │ ciaz          │ 2015  │ 7.45          │ 8.92          │ 42367      │
⋮
│ 291 │ amaze         │ 2014  │ 4.5           │ 6.4           │ 19000      │
│ 292 │ brio          │ 2015  │ 5.4           │ 6.1           │ 31427      │
│ 293 │ jazz          │ 2016  │ 6.4           │ 8.4           │ 12000      │
│ 294 │ city          │ 2010  │ 3.25          │ 9.9           │ 38000      │
│ 295 │ amaze         │ 2014  │ 3.75          │ 6.8           │ 33019      │
│ 296 │ city          │ 2015  │ 8.55          │ 13.09         │ 60076      │
│ 297 │ city          │ 2016  │ 9.5           │ 11.6          │ 33988      │
│ 298 │ brio          │ 2015  │ 4.0           │ 5.9           │ 60000      │
│ 299 │ city          │ 2009  │ 3.35          │ 11.0          │ 87934      │
│ 300 │ city          │ 2017  │ 11.5          │ 12.5          │ 9000       │
│ 301 │ brio          │ 2016  │ 5.3           │ 5.9           │ 5464       │

In [27]:
using DataFrames
df = DataFrame(:Year => df[:Year], :Price => df[:Selling_Price])

301×2 DataFrame
│ Row │ Year  │ Price   │
│     │ Int64 │ Float64 │
├─────┼───────┼─────────┤
│ 1   │ 2014  │ 3.35    │
│ 2   │ 2013  │ 4.75    │
│ 3   │ 2017  │ 7.25    │
│ 4   │ 2011  │ 2.85    │
│ 5   │ 2014  │ 4.6     │
│ 6   │ 2018  │ 9.25    │
│ 7   │ 2015  │ 6.75    │
│ 8   │ 2015  │ 6.5     │
│ 9   │ 2016  │ 8.75    │
│ 10  │ 2015  │ 7.45    │
⋮
│ 291 │ 2014  │ 4.5     │
│ 292 │ 2015  │ 5.4     │
│ 293 │ 2016  │ 6.4     │
│ 294 │ 2010  │ 3.25    │
│ 295 │ 2014  │ 3.75    │
│ 296 │ 2015  │ 8.55    │
│ 297 │ 2016  │ 9.5     │
│ 298 │ 2015  │ 4.0     │
│ 299 │ 2009  │ 3.35    │
│ 300 │ 2017  │ 11.5    │
│ 301 │ 2016  │ 5.3     │

In [28]:
for year in df[:Year]
    if year == Missing
        println("missing")
    end
end
for price in df[:Price]
    if price == Missing
        println("missing")
    end
end

In [29]:
using Lathe: preprocess

In [30]:
?(preprocess)

search:



|====== Lathe.preprocess =====

|____________/ Generalized Processing ___________

|_____preprocess.TrainTestSplit(array)

|_____preprocess.SortSplit(array)

|_____preprocess.UniformSplit(array)

|____________/ Feature Scaling ___________

|_____preprocess.Rescalar(array)

|_____preprocess.ArbitraryRescale(array)

|_____preprocess.MeanNormalization(array)

|_____preprocess.StandardScalar(array)

|____________/ Categorical Encoding ___________

|_____preprocess.OneHotEncode(array)

```

```


In [31]:
?(preprocess.TrainTestSplit)

TrainTestSplit takes either a DataFrame or an Array and splits it according to the at parameter.

---

[data] <- Iterable dictionary, dataframe, or Array.

a <- Percentage value used to determine a point to split the data.

---

```

```


In [32]:
train, test = preprocess._dfTrainTestSplit(df, .75)

(212×2 DataFrame
│ Row │ Year  │ Price   │
│     │ Int64 │ Float64 │
├─────┼───────┼─────────┤
│ 1   │ 2014  │ 3.35    │
│ 2   │ 2013  │ 4.75    │
│ 3   │ 2017  │ 7.25    │
│ 4   │ 2014  │ 4.6     │
│ 5   │ 2015  │ 6.5     │
│ 6   │ 2015  │ 7.45    │
│ 7   │ 2017  │ 2.85    │
│ 8   │ 2015  │ 6.85    │
│ 9   │ 2015  │ 6.1     │
│ 10  │ 2015  │ 7.25    │
⋮
│ 202 │ 2015  │ 5.75    │
│ 203 │ 2015  │ 8.4     │
│ 204 │ 2015  │ 5.4     │
│ 205 │ 2010  │ 3.25    │
│ 206 │ 2014  │ 3.75    │
│ 207 │ 2015  │ 8.55    │
│ 208 │ 2016  │ 9.5     │
│ 209 │ 2015  │ 4.0     │
│ 210 │ 2009  │ 3.35    │
│ 211 │ 2017  │ 11.5    │
│ 212 │ 2016  │ 5.3     │, 89×2 DataFrame
│ Row │ Year  │ Price   │
│     │ Int64 │ Float64 │
├─────┼───────┼─────────┤
│ 1   │ 2011  │ 2.85    │
│ 2   │ 2018  │ 9.25    │
│ 3   │ 2015  │ 6.75    │
│ 4   │ 2016  │ 8.75    │
│ 5   │ 2015  │ 7.5     │
│ 6   │ 2009  │ 2.25    │
│ 7   │ 2016  │ 7.75    │
│ 8   │ 2017  │ 4.9     │
│ 9   │ 2011  │ 4.4     │
│ 10  │ 2014  │ 6.0     │
⋮
│

In [33]:
test

89×2 DataFrame
│ Row │ Year  │ Price   │
│     │ Int64 │ Float64 │
├─────┼───────┼─────────┤
│ 1   │ 2011  │ 2.85    │
│ 2   │ 2018  │ 9.25    │
│ 3   │ 2015  │ 6.75    │
│ 4   │ 2016  │ 8.75    │
│ 5   │ 2015  │ 7.5     │
│ 6   │ 2009  │ 2.25    │
│ 7   │ 2016  │ 7.75    │
│ 8   │ 2017  │ 4.9     │
│ 9   │ 2011  │ 4.4     │
│ 10  │ 2014  │ 6.0     │
⋮
│ 79  │ 2015  │ 6.7     │
│ 80  │ 2009  │ 3.0     │
│ 81  │ 2015  │ 7.5     │
│ 82  │ 2010  │ 2.25    │
│ 83  │ 2015  │ 5.25    │
│ 84  │ 2006  │ 2.1     │
│ 85  │ 2014  │ 8.25    │
│ 86  │ 2016  │ 7.4     │
│ 87  │ 2016  │ 10.11   │
│ 88  │ 2014  │ 4.5     │
│ 89  │ 2016  │ 6.4     │

In [34]:
trainX = train[:Price]
trainY = train[:Year]
testX = test[:Price]
testY = test[:Year]

89-element Array{Int64,1}:
 2011
 2018
 2015
 2016
 2015
 2009
 2016
 2017
 2011
 2014
 2016
 2016
 2014
    ⋮
 2016
 2015
 2009
 2015
 2010
 2015
 2006
 2014
 2016
 2016
 2014
 2016

In [35]:
using Lathe: models


In [36]:
?(models.LinearRegression)

No documentation found.

Binding `Lathe.models.LinearRegression` does not exist.


In [41]:
?(models.SimpleLinearRegression)

Linear Regression is a well-known linear function used for predicting  continuous features with a mostly linear or semi-linear slope.

---

==PARAMETERS==

[y] <- Fill with your trainY values. Should be an array of shape (0,1) or (1,0)

[x] <- Fill in with your trainX values. Should be an array of shape (0,1) or (1,0)

---

==Functions==

predict(xt) <- Returns a prediction from the model based on the xtrain value passed (xt)


In [42]:
model = models.SimpleLinearRegression(trainX, trainY)

#7 (generic function with 1 method)

In [43]:
yhat = model.predict(testX)

89-element Array{Float64,1}:
 2013.4551444041285
 2014.1056789979405
 2013.8515639222326
 2014.054855982799
 2013.927798444945
 2013.3941567859586
 2013.9532099525159
 2013.6635187662089
 2013.6126957510673
 2013.7753293995204
 2013.470391308671
 2013.760082494978
 2013.7245063843789
    ⋮
 2013.8363170176901
 2013.8464816207186
 2013.470391308671
 2013.927798444945
 2013.3941567859586
 2013.699094876808
 2013.3789098814161
 2014.0040329676574
 2013.9176338419168
 2014.193094583984
 2013.6228603540956
 2013.8159878116335

In [44]:
yhat = [year = Int64(round(year)) for year in yhat]

89-element Array{Int64,1}:
 2013
 2014
 2014
 2014
 2014
 2013
 2014
 2014
 2014
 2014
 2013
 2014
 2014
    ⋮
 2014
 2014
 2013
 2014
 2013
 2014
 2013
 2014
 2014
 2014
 2014
 2014

In [45]:
stats.mae(yhat, testY)

0.0