In [2]:
str = "Hello"

"Hello"

In [3]:
mlstr = """I'm
A mult-line string"""

"I'm\nA mult-line string"

In [4]:
x = 5
"I think x = $x"

"I think x = 5"

In [5]:
macro px_str(s::String)
    """$s px"""
end

@px_str (macro with 1 method)

In [6]:
px"55"

"55 px"

In [10]:
vcat("hello ", "world!")

2-element Vector{String}:
 "hello "
 "world!"

In [12]:
join(["hello ", "world!"])

"hello world!"

In [23]:
join("hello ", "world!")

"hworld!eworld!lworld!lworld!oworld! "

In [15]:
"hello " * "world!"

"hello world!"

In [16]:
contains("hello", "h")

true

In [17]:
split("xyxyx", "y")

3-element Vector{SubString{String}}:
 "x"
 "x"
 "x"

In [19]:
replace("hello", "l" => "w")

"hewwo"

In [20]:
findnext("[", "[][]", 2)

3:3

In [22]:
findall("h", "hello, how are you? I am well, and you? I am well, as well.")

2-element Vector{UnitRange{Int64}}:
 1:1
 8:8

In [7]:
methods(string)

# 20 methods for generic function "string":
[1] string() in Base at strings/basic.jl:221
[2] string(x::T) where T<:Union{Float16, Float32, Float64} in Base.Ryu at ryu/Ryu.jl:121
[3] string(f::Printf.Spec{T}; modifier) where T in Printf at /opt/julia-1.6.3/julia-1.6.3/share/julia/stdlib/v1.7/Printf/src/Printf.jl:36
[4] string(t::Dates.Time) in Dates at /opt/julia-1.6.3/julia-1.6.3/share/julia/stdlib/v1.7/Dates/src/io.jl:44
[5] string(id::LibGit2.GitShortHash) in LibGit2 at /opt/julia-1.6.3/julia-1.6.3/share/julia/stdlib/v1.7/LibGit2/src/oid.jl:181
[6] string(b::BigFloat) in Base.MPFR at mpfr.jl:1013
[7] string(x::Dates.CompoundPeriod) in Dates at /opt/julia-1.6.3/julia-1.6.3/share/julia/stdlib/v1.7/Dates/src/periods.jl:347
[8] string(b::Bool) in Base at intfuncs.jl:790
[9] string(a::SubString{String}) in Base at strings/substring.jl:178
[10] string(mode::Pkg.GitTools.GitMode) in Pkg.GitTools at /opt/julia-1.6.3/julia-1.6.3/share/julia/stdlib/v1.7/Pkg/src/GitTools.jl:183
[11] string(n::BigInt; base, pad) in Base.GMP at gmp.jl:685
[12] string(n::Integer; base, pad) in Base at intfuncs.jl:771
[13] string(f::Random.DSFMT.GF2X) in Random.DSFMT at /opt/julia-1.6.3/julia-1.6.3/share/julia/stdlib/v1.7/Random/src/DSFMT.jl:108
[14] string(hash::Base.SHA1) in Base at loading.jl:106
[15] string(u::Base.UUID) in Base at uuid.jl:91
[16] string(a::Symbol) in Base at strings/io.jl:187
[17] string(a::String) in Base at strings/substring.jl:177
[18] string(a::Union{Char, SubString{String}, String}...) in Base at strings/substring.jl:208
[19] string(s::AbstractString) in Base at strings/basic.jl:222
[20] string(xs...) in Base at strings/io.jl:185

In [61]:
for char in "hello"
    println(char)
end

h
e
l
l
o


In [24]:
example_input = """{
    A : 5, 
    B : [5, 10, 15]
}"""

"{\n    A : 5, \n    B : [5, 10, 15]\n}"

In [57]:
function json_todct(s::String)
    s = replace(s, "\n" => "")
    s = replace(s, " " => "")
    s = replace(s, "}" => "")
    s = replace(s, "{" => "")
    empty::Vector = []
    dct::Dict = Dict()
    for pair in split(s, ",")
        if contains(pair, "[")
            push!(empty, pair)
        elseif contains(pair, "]")
            p = replace(pair, "]" => "")
            push!(empty, p)
            key = Symbol(split(empty[1], ":")[1])
            empty[1] = split(empty[1], ":")[2]
            empty[1] = replace(empty[1], "[" => "")
            val = [parse(Int64, e) for e in empty]
            push!(dct, key => val)
        elseif length(empty) > 0
            push!(empty, pair)
        elseif length(empty) == 0
            keyval = split(pair, ":")
            push!(dct, Symbol(keyval[1]) => parse(Int64, keyval[2]))
        end
    end
    dct
end

json_todct (generic function with 1 method)

In [58]:
json_todct(example_input)

Dict{Any, Any} with 2 entries:
  :A => 5
  :B => [5, 10, 15]

In [59]:
"hello"[2]

'e': ASCII/Unicode U+0065 (category Ll: Letter, lowercase)

In [60]:
"hello"[2:3]

"el"