# Indexing In Julia

In [1]:
array = [1, 2, 3, 4, 5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [2]:
array[1]

1

In [3]:
array[1:5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [4]:
?(getindex)

search: getindex



```
getindex(type[, elements...])
```

Construct a 1-d array of the specified type. This is usually called with the syntax `Type[]`. Element values can be specified using `Type[a,b,c,...]`.

# Examples

```jldoctest
julia> Int8[1, 2, 3]
3-element Vector{Int8}:
 1
 2
 3

julia> getindex(Int8, 1, 2, 3)
3-element Vector{Int8}:
 1
 2
 3
```

---

```
getindex(collection, key...)
```

Retrieve the value(s) stored at the given key or index within a collection. The syntax `a[i,j,...]` is converted by the compiler to `getindex(a, i, j, ...)`.

See also [`get`](@ref), [`keys`](@ref), [`eachindex`](@ref).

# Examples

```jldoctest
julia> A = Dict("a" => 1, "b" => 2)
Dict{String, Int64} with 2 entries:
  "b" => 2
  "a" => 1

julia> getindex(A, "a")
1
```

---

```
getindex(A, inds...)
```

Return a subset of array `A` as specified by `inds`, where each `ind` may be, for example, an `Int`, an [`AbstractRange`](@ref), or a [`Vector`](@ref). See the manual section on [array indexing](@ref man-array-indexing) for details.

# Examples

```jldoctest
julia> A = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> getindex(A, 1)
1

julia> getindex(A, [2, 1])
2-element Vector{Int64}:
 3
 1

julia> getindex(A, 2:4)
3-element Vector{Int64}:
 3
 2
 4
```

---

```
getindex(tree::GitTree, target::AbstractString) -> GitObject
```

Look up `target` path in the `tree`, returning a [`GitObject`](@ref) (a [`GitBlob`](@ref) in the case of a file, or another [`GitTree`](@ref) if looking up a directory).

# Examples

```julia
tree = LibGit2.GitTree(repo, "HEAD^{tree}")
readme = tree["README.md"]
subtree = tree["test"]
runtests = subtree["runtests.jl"]
```


In [5]:
import Base: getindex, setindex!

In [6]:
mutable struct NotACollection
    x::Int64
end

In [7]:
getindex(notcol::NotACollection, y::Int64) = notcol.x

getindex (generic function with 220 methods)

In [8]:
notacol = NotACollection(5)

NotACollection(5)

In [9]:
notacol[1]

5

In [10]:
setindex!(notcol::NotACollection, y::Int64, val::Int64) = notcol.x = y

setindex! (generic function with 90 methods)

In [11]:
notacol[1] = 10

10

In [12]:
println(notacol[1])

10


# Useful Methods

In [13]:
nums = [54, 33, 22, 13]

4-element Vector{Int64}:
 54
 33
 22
 13

In [14]:
size(nums)

(4,)

In [15]:
println(typeof(size(nums)))

Tuple{Int64}


In [16]:
println(size(nums)[1])

4


In [17]:
push!(nums, 5)

5-element Vector{Int64}:
 54
 33
 22
 13
  5

In [18]:
append!(nums, 5)

6-element Vector{Int64}:
 54
 33
 22
 13
  5
  5

In [19]:
nums = Array{Any}(nums)
append!(nums, 5.5)

7-element Vector{Any}:
 54
 33
 22
 13
  5
  5
  5.5

In [20]:
filter((x) -> x == 5, nums)

2-element Vector{Any}:
 5
 5

In [21]:
r = 5:10

5:10

In [22]:
collect(r)

6-element Vector{Int64}:
  5
  6
  7
  8
  9
 10

In [23]:
?(findall)

search: findall findmax! findmax findlast



```
findall(f::Function, A)
```

Return a vector `I` of the indices or keys of `A` where `f(A[I])` returns `true`. If there are no such elements of `A`, return an empty array.

Indices or keys are of the same type as those returned by [`keys(A)`](@ref) and [`pairs(A)`](@ref).

# Examples

```jldoctest
julia> x = [1, 3, 4]
3-element Vector{Int64}:
 1
 3
 4

julia> findall(isodd, x)
2-element Vector{Int64}:
 1
 2

julia> A = [1 2 0; 3 4 0]
2×3 Matrix{Int64}:
 1  2  0
 3  4  0
julia> findall(isodd, A)
2-element Vector{CartesianIndex{2}}:
 CartesianIndex(1, 1)
 CartesianIndex(2, 1)

julia> findall(!iszero, A)
4-element Vector{CartesianIndex{2}}:
 CartesianIndex(1, 1)
 CartesianIndex(2, 1)
 CartesianIndex(1, 2)
 CartesianIndex(2, 2)

julia> d = Dict(:A => 10, :B => -1, :C => 0)
Dict{Symbol, Int64} with 3 entries:
  :A => 10
  :B => -1
  :C => 0

julia> findall(x -> x >= 0, d)
2-element Vector{Symbol}:
 :A
 :C

```

---

```
findall(A)
```

Return a vector `I` of the `true` indices or keys of `A`. If there are no such elements of `A`, return an empty array. To search for other kinds of values, pass a predicate as the first argument.

Indices or keys are of the same type as those returned by [`keys(A)`](@ref) and [`pairs(A)`](@ref).

See also: [`findfirst`](@ref), [`searchsorted`](@ref).

# Examples

```jldoctest
julia> A = [true, false, false, true]
4-element Vector{Bool}:
 1
 0
 0
 1

julia> findall(A)
2-element Vector{Int64}:
 1
 4

julia> A = [true false; false true]
2×2 Matrix{Bool}:
 1  0
 0  1

julia> findall(A)
2-element Vector{CartesianIndex{2}}:
 CartesianIndex(1, 1)
 CartesianIndex(2, 2)

julia> findall(falses(3))
Int64[]
```

---

```
findall(
    pattern::Union{AbstractString,AbstractPattern},
    string::AbstractString;
    overlap::Bool = false,
)
```

Return a `Vector{UnitRange{Int}}` of all the matches for `pattern` in `string`. Each element of the returned vector is a range of indices where the matching sequence is found, like the return value of [`findnext`](@ref).

If `overlap=true`, the matching sequences are allowed to overlap indices in the original string, otherwise they must be from disjoint character ranges.

# Examples

```jldoctest
julia> findall("a", "apple")
1-element Vector{UnitRange{Int64}}:
 1:1

julia> findall("nana", "banana")
1-element Vector{UnitRange{Int64}}:
 3:6

julia> findall("a", "banana")
3-element Vector{UnitRange{Int64}}:
 2:2
 4:4
 6:6
```

!!! compat "Julia 1.3"
    This method requires at least Julia 1.3.


---

```
findall(c::AbstractChar, s::AbstractString)
```

Return a vector `I` of the indices of `s` where `s[i] == c`. If there are no such elements in `s`, return an empty array.

# Examples

```jldoctest
julia> findall('a', "batman")
2-element Vector{Int64}:
 2
 5
```

!!! compat "Julia 1.7"
    This method requires at least Julia 1.7.



In [24]:
z = findall(x -> x == 5, nums)

2-element Vector{Int64}:
 5
 6

In [25]:
array = [nums[x] for x in z]

2-element Vector{Int64}:
 5
 5

In [26]:
while length(nums) > 1
    deleteat!(nums, 1)
end

In [27]:
println(nums)

Any[5.5]
