# Introduction
Within the past few years of very rapid development in data science technology, we have seen the dramatic escalation and adoption of a multitude of open-source tools. Among these are well-known tools like SkLearn and Tensorflow. With the recent early adoption of Julia, however, there are oppurtunities to dramatically improve our strategic approaches to solving machine-learning problems. The problem that effects the Julia language most is easily the lack of mature packages for various science or data related operations. While this has been a long road that is certainly still being traveled, I think it is work taking a look at what Julia has to offer in its current state that hadn't been there before. One recent addition I have been excited about is the addition of a Random Forest Classifier to Lathe. Using Lathe, DataFrames, and CSV, we can now easily explore, encode, and predict with various features!

In [1]:
using DataFrames, PrettyTables
using CSV

In [2]:
using DataFrames; df = CSV.read("car data.csv", DataFrame)

301×9 DataFrame
 Row │ Car_Name       Year   Selling_Price  Present_Price  Kms_Driven  Fuel_Ty ⋯
     │ String         Int64  Float64        Float64        Int64       String  ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ ritz            2014           3.35           5.59       27000  Petrol  ⋯
   2 │ sx4             2013           4.75           9.54       43000  Diesel
   3 │ ciaz            2017           7.25           9.85        6900  Petrol
   4 │ wagon r         2011           2.85           4.15        5200  Petrol
   5 │ swift           2014           4.6            6.87       42450  Diesel  ⋯
   6 │ vitara brezza   2018           9.25           9.83        2071  Diesel
   7 │ ciaz            2015           6.75           8.12       18796  Petrol
   8 │ s cross         2015           6.5            8.61       33429  Diesel
   9 │ ciaz            2016           8.75           8.89       20273  Diesel  ⋯
  10 │ ciaz            2015           7.45           8.92       42367  Diesel
  11 │ alto 800        2017           2.85           3.6         2135  Petrol
  ⋮  │       ⋮          ⋮          ⋮              ⋮            ⋮           ⋮   ⋱
 292 │ brio            2015           5.4            6.1        31427  Petrol
 293 │ jazz            2016           6.4            8.4        12000  Petrol  ⋯
 294 │ city            2010           3.25           9.9        38000  Petrol
 295 │ amaze           2014           3.75           6.8        33019  Petrol
 296 │ city            2015           8.55          13.09       60076  Diesel
 297 │ city            2016           9.5           11.6        33988  Diesel  ⋯
 298 │ brio            2015           4.0            5.9        60000  Petrol
 299 │ city            2009           3.35          11.0        87934  Petrol
 300 │ city            2017          11.5           12.5         9000  Diesel
 301 │ brio            2016           5.3            5.9         5464  Petrol  ⋯
                                                  4 columns and 280 rows omitted

In [3]:
show(df, allcols = true)

301×9 DataFrame
 Row │ Car_Name       Year   Selling_Price  Present_Price  Kms_Driven  Fuel_Type  Seller_Type  Transmission  Owner 
     │ String         Int64  Float64        Float64        Int64       String     String       String        Int64 
─────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1 │ ritz            2014           3.35           5.59       27000  Petrol     Dealer       Manual            0
   2 │ sx4             2013           4.75           9.54       43000  Diesel     Dealer       Manual            0
   3 │ ciaz            2017           7.25           9.85        6900  Petrol     Dealer       Manual            0
   4 │ wagon r         2011           2.85           4.15        5200  Petrol     Dealer       Manual            0
   5 │ swift           2014           4.6            6.87       42450  Diesel     Dealer       Manual            0
   6 │ vitara brezza   2018           9.25           9.83    

In [4]:
Set(df[!, :Transmission])

Set{String} with 2 elements:
  "Manual"
  "Automatic"

In [5]:
Set(df[!, :Fuel_Type])

Set{String} with 3 elements:
  "Diesel"
  "CNG"
  "Petrol"

In [6]:
Set(df[!, :Seller_Type])

Set{String} with 2 elements:
  "Dealer"
  "Individual"

In [7]:
mldf = DataFrame(:Fuel => df[!, :Fuel_Type], :Kms => df[!, :Kms_Driven])

301×2 DataFrame
 Row │ Fuel    Kms   
     │ String  Int64 
─────┼───────────────
   1 │ Petrol  27000
   2 │ Diesel  43000
   3 │ Petrol   6900
   4 │ Petrol   5200
   5 │ Diesel  42450
   6 │ Diesel   2071
   7 │ Petrol  18796
   8 │ Diesel  33429
   9 │ Diesel  20273
  10 │ Diesel  42367
  11 │ Petrol   2135
  ⋮  │   ⋮       ⋮
 292 │ Petrol  31427
 293 │ Petrol  12000
 294 │ Petrol  38000
 295 │ Petrol  33019
 296 │ Diesel  60076
 297 │ Diesel  33988
 298 │ Petrol  60000
 299 │ Petrol  87934
 300 │ Diesel   9000
 301 │ Petrol   5464
     280 rows omitted

In [8]:
using Lathe.preprocess: TrainTestSplit
train, test = TrainTestSplit(mldf)

(225×2 DataFrame
 Row │ Fuel    Kms   
     │ String  Int64 
─────┼───────────────
   1 │ Petrol  27000
   2 │ Diesel  43000
   3 │ Petrol   6900
   4 │ Petrol   5200
   5 │ Diesel  42450
   6 │ Diesel   2071
   7 │ Diesel  33429
   8 │ Diesel  20273
   9 │ Petrol   2135
  10 │ Petrol  15000
  11 │ Petrol  26000
  ⋮  │   ⋮       ⋮
 216 │ Petrol  19000
 217 │ Petrol  31427
 218 │ Petrol  38000
 219 │ Petrol  33019
 220 │ Diesel  60076
 221 │ Diesel  33988
 222 │ Petrol  60000
 223 │ Petrol  87934
 224 │ Diesel   9000
 225 │ Petrol   5464
     204 rows omitted, 76×2 DataFrame
 Row │ Fuel    Kms   
     │ String  Int64 
─────┼───────────────
   1 │ Petrol  18796
   2 │ Diesel  42367
   3 │ Diesel  51000
   4 │ Petrol   2400
   5 │ Petrol  50000
   6 │ Petrol  45280
   7 │ Petrol  56879
   8 │ Petrol  20000
   9 │ Petrol  44542
  10 │ Diesel  45000
  11 │ Diesel  45000
  ⋮  │   ⋮       ⋮
  67 │ Petrol  31427
  68 │ Diesel  48000
  69 │ Petrol  49562
  70 │ Petrol   5600
  71 │ Petrol  6120

In [9]:
X = :Kms
Y = :Fuel

:Fuel

In [10]:
trainX = train[!, X]
trainy = train[!, Y]
testX = test[!, X]
testy = test[!, Y]

76-element PooledArrays.PooledArray{String,UInt32,1,Array{UInt32,1}}:
 "Petrol"
 "Diesel"
 "Diesel"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Diesel"
 "Diesel"
 "Petrol"
 "Petrol"
 ⋮
 "Diesel"
 "Diesel"
 "Petrol"
 "Diesel"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"

In [11]:
using Lathe.models: majClassBaseline

In [12]:
?(majClassBaseline)

search:



Majority class baseline is used to find the most often interpreted  classification in an array.

---

==PARAMETERS==

[y] <- Fill with your trainY values. Should be an array of shape (0,1) or (1,0)

---

==Functions==

predict(xt) <- Returns a prediction from the model based on the xtrain value passed (xt)

counts() <- Returns a dictionary with the counts of all inserted keys.

highest() <- Will return a Dictionary key with the count as well as the value for the most interpreted classification.


In [13]:
evaluation = majClassBaseline(trainy)

#37 (generic function with 1 method)

In [14]:
yhat = evaluation.predict(testX)

76-element Array{String,1}:
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 ⋮
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"

In [15]:
using Lathe.lstats: catacc

In [16]:
?(catacc)

search: catch_backtrace CrayonStack CartesianIndices



Categorical accuracy is used to determine the accuracy of a categorical model by calculating the percentage of correct predictions.

---

testy = ["hi","hello"]

yhat = ["hi","hi"]

accuracy = catacc(yhat,testy)

.5


In [17]:
catacc(yhat, testy)

0.8552631578947368

In [18]:
evaluation.counts()

3-element Array{Pair{String,Int64},1}:
    "CNG" => 2
 "Diesel" => 49
 "Petrol" => 174

In [19]:
using Lathe.models: RandomForestClassifier

In [20]:
?(RandomForestClassifier)

search:



## Random Forest Classifier

### Description

The Random Forest Classifier uses a multitude of decision trees to   solve classification problems.

---

### Input

RandomForestClassifier(x, y, rng ;   max*depth = 6, min*node*records = 1, n*trees = 100)

---

#### Positional Arguments

Array{Any} - X:: Array of x's for which the model will use to   predict y.

Array{Any} - Y:: Array of y's for which the x's are used to predict.

RandomNumberGenerator - rng:: Determines the seed for the given model.

#### Key-word Arguments

Int64 - max_depth:: Determines the max depth which the tree should use   as a stop parameter.

Int64 - min*node*records:: Determines the minimum number of nodes a   constructed node is allowed to have.

## Int64 - n_trees:: Determines how many decision trees should be trained.

### Output

model:: A Lathe Model.

---

### Functions

Model.predict(xt) :: Predicts a new y based on the data provided as xt and   the weights obtained from X.

---

### Data

storedata :: A tree node type that contains the weights and their  corresponding values.


In [21]:
model = RandomForestClassifier(trainX, trainy)

#15 (generic function with 1 method)

In [22]:
yhat = model.predict(testX)

76-element Array{String,1}:
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Diesel"
 ⋮
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Diesel"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"

In [23]:
Set(yhat)

Set{String} with 2 elements:
  "Diesel"
  "Petrol"

In [24]:
catacc(yhat, testy)

0.8026315789473685

In [25]:
model = RandomForestClassifier(trainX, trainy, n_trees = 100, max_depth = 11)

#15 (generic function with 1 method)

In [26]:
yhat = model.predict(testX)

76-element Array{String,1}:
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Diesel"
 ⋮
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Diesel"
 "Petrol"
 "Petrol"
 "Petrol"
 "Diesel"
 "Petrol"

In [27]:
catacc(yhat, testy)

0.8026315789473685

In [28]:
model = RandomForestClassifier(trainX, trainy, n_trees = 1500, max_depth = 5)

yhat = model.predict(testX)

76-element Array{String,1}:
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Diesel"
 ⋮
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Diesel"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"

In [29]:
catacc(yhat, testy)

0.8026315789473685

In [30]:
using Lathe.preprocess: StandardScaler

In [31]:
?(StandardScaler)

search:



## Standard Scaler

### Description

Normalizes an array using the z (Normal) distribution.

---

### Input

StandardScaler(x)

---

#### Positional Arguments

Array{Any} - x:: Array for which the original scaler should be based   off of.

---

### Output

## scalar :: A Lathe Preprocesser object.

### Functions

Preprocesser.predict(xt) :: Applies the scaler to xt.

---

### Data

dist  :: Returns the normal distribution object for which this scaler uses.


In [32]:
scaler = StandardScaler(trainX)

#33 (generic function with 1 method)

In [33]:
trainX = scaler.predict(trainX)

225-element Array{Complex{Float64},1}:
 -59.690787567795894 + 0.0im
  21.589116586419653 - 0.0im
 -161.79866716152918 + 0.0im
 -170.43465697791456 + 0.0im
   18.79511988111849 - 0.0im
 -186.32995823407336 + 0.0im
  -27.03150607983016 + 0.0im
  -93.86390727063389 + 0.0im
 -186.00483861745647 + 0.0im
 -120.65071568345755 + 0.0im
  -64.77078157743436 + 0.0im
   196.4780703562433 - 0.0im
  21.589116586419653 - 0.0im
                     ⋮
  -24.13082950032659 + 0.0im
 -141.07229160220422 + 0.0im
 -100.33073964490366 + 0.0im
  -37.20165408712638 + 0.0im
  -3.810853461772706 + 0.0im
 -29.114303623781932 + 0.0im
  108.33509429500619 - 0.0im
 -24.191789428442252 + 0.0im
  107.94901475027366 - 0.0im
  249.85356741551473 - 0.0im
  -151.1306797412884 + 0.0im
 -169.09353855937002 + 0.0im

In [34]:
testX = scaler.predict(testX)

76-element Array{Complex{Float64},1}:
 -101.36705842286992 + 0.0im
  18.373480378318497 - 0.0im
   62.22906866352742 - 0.0im
  -184.6586402049023 + 0.0im
   57.14907465388895 - 0.0im
   33.17150292839537 - 0.0im
     92.094353446192 - 0.0im
  -95.25074563526519 + 0.0im
  29.422467349282176 - 0.0im
  31.749104605696594 - 0.0im
  31.749104605696594 - 0.0im
   50.88544204000472 - 0.0im
  118.10900276955061 - 0.0im
                     ⋮
   52.06908064425048 - 0.0im
 -14.306121085685788 + 0.0im
  -37.20165408712638 + 0.0im
   46.98908663461201 - 0.0im
    54.9240372776673 - 0.0im
 -168.40265937405917 + 0.0im
  114.06024754386874 - 0.0im
  -40.62557004962271 + 0.0im
  -86.20835629810871 + 0.0im
 -176.53064978948075 + 0.0im
   -151.079879801192 + 0.0im
 -135.89069771237297 + 0.0im

In [35]:
trainX = Array{Real}(trainX)
testX = Array{Real}(testX)

76-element Array{Real,1}:
 -101.36705842286992
   18.373480378318497
   62.22906866352742
 -184.6586402049023
   57.14907465388895
   33.17150292839537
   92.094353446192
  -95.25074563526519
   29.422467349282176
   31.749104605696594
   31.749104605696594
   50.88544204000472
  118.10900276955061
    ⋮
   52.06908064425048
  -14.306121085685788
  -37.20165408712638
   46.98908663461201
   54.9240372776673
 -168.40265937405917
  114.06024754386874
  -40.62557004962271
  -86.20835629810871
 -176.53064978948075
 -151.079879801192
 -135.89069771237297

In [50]:
model = RandomForestClassifier(trainX, trainy, n_trees = 1500, max_depth = 3)

yhat = model.predict(testX)

76-element Array{String,1}:
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 ⋮
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"
 "Petrol"

In [51]:
catacc(yhat, testy)

0.8552631578947368

In [52]:
?(RandomForestClassifier)

search:



## Random Forest Classifier

### Description

The Random Forest Classifier uses a multitude of decision trees to   solve classification problems.

---

### Input

RandomForestClassifier(x, y, rng ;   max*depth = 6, min*node*records = 1, n*trees = 100)

---

#### Positional Arguments

Array{Any} - X:: Array of x's for which the model will use to   predict y.

Array{Any} - Y:: Array of y's for which the x's are used to predict.

RandomNumberGenerator - rng:: Determines the seed for the given model.

#### Key-word Arguments

Int64 - max_depth:: Determines the max depth which the tree should use   as a stop parameter.

Int64 - min*node*records:: Determines the minimum number of nodes a   constructed node is allowed to have.

## Int64 - n_trees:: Determines how many decision trees should be trained.

### Output

model:: A Lathe Model.

---

### Functions

Model.predict(xt) :: Predicts a new y based on the data provided as xt and   the weights obtained from X.

---

### Data

storedata :: A tree node type that contains the weights and their  corresponding values.


In [83]:
model = RandomForestClassifier(trainX, trainy, n_trees = 10, max_depth = 2, min_node_records = 4)

yhat = model.predict(testX)

catacc(yhat, testy)

0.8552631578947368