# The push!() Method
The Julia programming language has a rich and extended base that is capable of a surprising amount of things on its own. What sets Julia apart from many other programming languages is its robust type system. The method system of course accompanies this quite well, however the type system is what really tends to steal the show. There are also some great methods that work with types all across Julia. If you have been using Julia for some time, it is likely that you might have encountered the push!() method in the wild. The method is commonly used because it is a core feature of Julia. That being said, those who are interested in Julia might want to get some experience working with it.
## The Basics

In [1]:
example = [9, 7, 4, 28]

4-element Vector{Int64}:
  9
  7
  4
 28

In [2]:
?(push!)

search: push! pushfirst! pushdisplay



```
push!(collection, items...) -> collection
```

Insert one or more `items` in `collection`. If `collection` is an ordered container, the items are inserted at the end (in the given order).

# Examples

```jldoctest
julia> push!([1, 2, 3], 4, 5, 6)
6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
```

If `collection` is ordered, use [`append!`](@ref) to add all the elements of another collection to it. The result of the preceding example is equivalent to `append!([1, 2, 3], [4, 5, 6])`. For `AbstractSet` objects, [`union!`](@ref) can be used instead.

See [`sizehint!`](@ref) for notes about the performance model.

See also [`pushfirst!`](@ref).


In [3]:
push!(example, 5)

5-element Vector{Int64}:
  9
  7
  4
 28
  5

In [4]:
example[5]

5

In [5]:
push!(Array{Any}(example), 1:5)

6-element Vector{Any}:
  9
  7
  4
 28
  5
   1:5

In [27]:
import Base: push!

In [39]:
"""## push!(collection::Vector{Int64}, range::UnitRange)
This method can be used to unpack a range generator and return its elements pushed into the collection. \
```
julia> push!([2, 3] 1:2)

4-element Vector{Int64}
2
3
1
2
```

"""
function push!(collection::Vector{Int64}, range::UnitRange)
    [push!(collection, i) for i in range]
end

Base.push!

In [40]:
?(push!)

search: push! pushfirst! push6 pushdisplay



```
push!(collection, items...) -> collection
```

Insert one or more `items` in `collection`. If `collection` is an ordered container, the items are inserted at the end (in the given order).

# Examples

```jldoctest
julia> push!([1, 2, 3], 4, 5, 6)
6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
```

If `collection` is ordered, use [`append!`](@ref) to add all the elements of another collection to it. The result of the preceding example is equivalent to `append!([1, 2, 3], [4, 5, 6])`. For `AbstractSet` objects, [`union!`](@ref) can be used instead.

See [`sizehint!`](@ref) for notes about the performance model.

See also [`pushfirst!`](@ref).

---

## push!(collection::Vector{Int64}, range::UnitRange)

This method can be used to unpack a range generator and return its elements pushed into the collection.

```
julia> push!([2, 3] 1:2)

4-element Vector{Int64}
2
3
1
2
```


In [42]:
?(push!(::Vector{Int64}, ::UnitRange))

## push!(collection::Vector{Int64}, range::UnitRange)

This method can be used to unpack a range generator and return its elements pushed into the collection.

```
julia> push!([2, 3] 1:2)

4-element Vector{Int64}
2
3
1
2
```


In [41]:
example = Vector{Int64}(example[1:5])

5-element Vector{Int64}:
  9
  7
  4
 28
  5

In [34]:
push!(example, 1:5)

5-element Vector{Vector{Int64}}:
 [9, 7, 4, 28, 5, 1, 2, 3, 4, 5]
 [9, 7, 4, 28, 5, 1, 2, 3, 4, 5]
 [9, 7, 4, 28, 5, 1, 2, 3, 4, 5]
 [9, 7, 4, 28, 5, 1, 2, 3, 4, 5]
 [9, 7, 4, 28, 5, 1, 2, 3, 4, 5]

In [35]:
example

10-element Vector{Int64}:
  9
  7
  4
 28
  5
  1
  2
  3
  4
  5

In [10]:
Array(1:5)

5-element Vector{Int64}:
 1
 2
 3
 4
 5