#### comparison and overview

In [57]:
module Example

abstract type SuperType <: Any end
                      # ^ (this is also implicit, doesn't need to be typed)
mutable struct Type <: SuperType
    field::Int64
   # ^ field  ^ field type
     function SuperType()
            # ^ inner constructor
           # v call to `new`, providing our fields
           new(0)
     end
end

function sample_function(sample_argument::Type)

end

# exports
export sample_function
end

Main.Example

In [58]:
mutable struct File{T <: Any}
    uri::Vector{SubString}
    name::String
    function File(uri::String)
        splits = split(uri, "/")
        file_extension = split(splits[length(splits)], ".")
        file_extension = Symbol(file_extension[2:length(file_extension)])
        new{file_extension}(splits, length(splits))::File{T}
    end
end

function turn_into_document(file::File{:doc})

end

function turn_into_document(file::File{:docx})
    
end

turn_into_document (generic function with 2 methods)

```python
class File:
    def __init__(self, uri):
        self.uri = uri.split("/")
        self.name = self.uri[len(self.uri)]

class DocFile(File):
    def turn_into_document(self):
        pass

class DocXFile(File):
    def turn_into_document(self):
        pass
```

#### key differences between python and julia

```python
class Vehicle:
    def __init__(self, model, horsepower, weight, distance, time):
        self.model = model
        self.distance = distance
        self.hp = horsepower
        self.time = time
    def get_speed():
        self.distance / self.time

class Car(Vehicle):
    pass
# both __init__ and get_speed are inherited.
class Truck(Vehicle):
    def __init__(self, model, horsepower, weight, distance, time, truck_class, capacity):
        self.model = model
        self.distance = distance
        self.hp = horsepower
        self.time = time
        self.truck_class = truck_class
        self.capacity = capacity
    # get_speed is inherited, __init__ is `overloaded`
```

In [59]:
abstract type AbstractData end

struct EnumeratedData <: AbstractData
    number::Int64
    data::String
end

struct LabeledData <: AbstractData
    name::String
    data::String
end

function show_data(t::AbstractData)
    print(join(data * "\n" for data in split(t.data, ";")))
end

show_data (generic function with 1 method)

In [60]:
methods(show_data)

# 1 method for generic function "show_data" from Main:
 [1] show_data(t::AbstractData)
     @ In[59]:13

In [61]:
function no_methods end
methods(no_methods)

# 0 methods for generic function "no_methods" from Main

In [62]:
struct ExampleType
   field::Int64
end

In [63]:
mutable struct MutableExampleType
    field::Int64
end

In [64]:
mutable struct MutableExampleTypeWithImmutableField
    const field::Int64
end

In [65]:
mutable struct Constructor
    # fields
   id::Int64
   name::String
     # v inner constructor
   function Constructor(name::String)
      # v inner constructor = use `new`
       new(rand(1:20), name)::Constructor
   end
end # - Constructor

# outer constructor:
Constructor() = Constructor("Unnamed")

Constructor

In [66]:
abstract type Vehicle end

In [67]:
abstract type Car <: Vehicle end

mutable struct Civic <: Car
    year::Int64
    value::Float64
end

In [68]:
car = Civic(2003, 2023.27)

println(Car <: Vehicle)
println(Civic <: Car)
println(Civic <: Vehicle)
println(typeof(car) <: Car && Car <: Vehicle)
println(Vehicle <: Car)

true
true
true
true
false


In [69]:
myvec = [5, 10, 15, 20]

println(typeof(myvec))

Vector{Int64}


In [70]:
function type_of_vec(vec::Vector{<:Any})
    println("a type we haven't made a function for, $(typeof(vec))")
end

function type_of_vec(vec::Vector{<:Number})
    println("some kind of numerical vector")
end

function type_of_vec(vec::Vector{Int64})
  println("this is a Vector of numbers")
end

function type_of_vec(vec::Vector{<:AbstractString})
    println("a vector of strings")
end

type_of_vec (generic function with 4 methods)

In [71]:
display(typeof(myvec))

Vector{Int64} (alias for Array{Int64, 1})

In [72]:
# parameter T and N vv
mutable struct MyArray{T <: Any, N}
    dims::Vector{T}   #^
       #  ^^ of type Vector{T}
   
              #     vv providing parameters
    function MyArray{T, N}(dims::T ...) where {T <: Any, N <: Any}
        new{T, N}(Vector{T}([dim for dim in dims]))
    end
end

In [73]:
new_mat = [1 4 7; 2 5 8; 3 6 9]

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [74]:
const MyVector{T} = MyArray{T, 1}

MyVector (alias for MyArray{T, 1} where T)

In [75]:
function infinite_values(x::Int64 ...)
     # x is a tuple
    println(x)
    allocated = [x ...]
    # ^ converting x to an allocated `Vector`
end

infinite_values(10, 11, 22, 33)

(10, 11, 22, 33)

(10, 11, 22, 33)


(10, 11, 22, 33)

In [76]:
example() = begin # <- the begin is only necessary for multi-line

end

example (generic function with 1 method)

In [77]:
mean(x::Vector{<:Number}) = sum(x) / len(x)

mean (generic function with 1 method)

In [78]:
# v argument
new_function = x::Int64 -> x += 5

multi_line_andarg = (x::Int64, y::Float64) -> begin
     x += y
     x * y
end

#31 (generic function with 1 method)

In [79]:
myvec = [5, 6, 11, 12]

# `filter!` will remove values according to our conditional response.
filter!(myvec) do value::Int64
    value < 11
end

println(myvec)

[5, 6]


In [80]:
myvec = [5, 6, 11, 12]
x = filter(myvec) do value::Int64
    value < 11
end

println(myvec)
println(x)

[5, 6, 11, 12]
[5, 6]


```python
new_dict = {"key" : "value", "key" : "value"}
```

In [81]:
pair = :A => 1

:A => 1

In [82]:
my_dict = Dict(:A => [1, 2, 3], :B => [1, 2, 3])

Dict{Symbol, Vector{Int64}} with 2 entries:
  :A => [1, 2, 3]
  :B => [1, 2, 3]

In [83]:
push!(my_dict, :C => [4, 5, 6])
for pair in my_dict
    println(pair)
    println("key: $(pair[1])")
    println("value: $(pair[2])")
end

:A => [1, 2, 3]
key: A
value: [1, 2, 3]
:B => [1, 2, 3]
key: B
value: [1, 2, 3]
:C => [4, 5, 6]
key: C
value: [4, 5, 6]


In [84]:
import Base: getindex, setindex!

mutable struct Person
    name::String
end

function getindex(vector_of_person::Vector{Person}, name::String)
    first_found = findfirst(person::Person -> person.name == name, vector_of_person)
    if isnothing(first_found)
        throw(BoundsError())
    end
    vector_of_person[first_found]
end

function setindex!(vector_of_person::Vector{Person}, new_name::String, name::String)
    first_found = findfirst(person::Person -> person.name == name, vector_of_person)
    if isnothing(first_found)
        throw(BoundsError())
    end
    vector_of_person[first_found].name = new_name
end

p = Person("Emma")
p2 = Person("Oliver")

vec = [p, p2]

println(vec["Emma"])

vec["Oliver"] = "Thomas"

println(vec)

Person("Emma")
Person[Person("Emma"), Person("Thomas")]


In [85]:
vec = Vector{Int64}()
push!(vec, 1, 2)

append!(vec, [3, 4, 5])

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [86]:
push!(vec, [1 , 1, 8])

LoadError: MethodError: Cannot `convert` an object of type Vector{Int64} to an object of type Int64

Closest candidates are:
  convert(::Type{T}, ::Base.TwicePrecision) where T<:Number
   @ Base twiceprecision.jl:273
  convert(::Type{T}, ::AbstractChar) where T<:Number
   @ Base char.jl:185
  convert(::Type{T}, ::CartesianIndex{1}) where T<:Number
   @ Base multidimensional.jl:127
  ...


In [87]:
vec = Vector(1:5)
insert!(vec, 3, 100)

6-element Vector{Int64}:
   1
   2
 100
   3
   4
   5

In [88]:
vcat([5, 10, 15], [-5, -10, -15])

6-element Vector{Int64}:
   5
  10
  15
  -5
 -10
 -15

In [89]:
hcat([-5, -10, -15], [5, 10, 15])

3×2 Matrix{Int64}:
  -5   5
 -10  10
 -15  15

In [90]:
data = Dict{String, String}("Al" => "127.0.0.1", "John" => "127.0.0.8")

more_data = Dict{String, String}("Hank" => "192.168.0.1")

merged = merge(more_data, data)

Dict{String, String} with 3 entries:
  "Al"   => "127.0.0.1"
  "John" => "127.0.0.8"
  "Hank" => "192.168.0.1"

In [91]:
using Statistics

numbers = [rand(1:1000) for x in 1:1000]
function normalize(x::Number, mu::Number, std::Number)
    (x - mu) / std
end

println(broadcast(normalize, numbers, length(numbers) / sum(numbers), Statistics.std(numbers)))

[0.8386780448071021, 1.7252877141243237, 2.7933271613327144, 2.2832698612235793, 2.4989316726791198, 2.115532896758159, 0.05818767953943194, 1.9272567121541158, 2.8857536519565175, 2.961064125798135, 0.5682449796485672, 0.2841191010642838, 0.7667907743219219, 3.1253778869071183, 0.20538542386622938, 0.4313168453910812, 2.4236211988375023, 1.3145033113518658, 1.9683351524313615, 2.759095127768343, 1.1159575166785112, 2.5639725364514256, 1.8279838148174383, 2.827559194897086, 0.8044460112427305, 0.9002957052229706, 1.4480082422529146, 1.95806554236205, 2.7864807546198405, 0.10268932317311488, 0.5237433360148842, 0.2293478473612894, 1.5815131731539633, 0.7325587407575503, 3.234920394313107, 0.030802052687934744, 1.2665784643617457, 1.4171994120449802, 1.0509166529062053, 2.1908433705997763, 1.1673055670250683, 0.3320439480544039, 3.0500674130655008, 1.0783022797577024, 1.4000833952627945, 2.697477467352474, 1.2220768207280628, 2.372273148490945, 0.32862074469796676, 1.6123220033618977, 3.

In [92]:
sample_vec = [1, 2, 3, 4, 5]

println(findall(x -> x < 3, sample_vec))

[1, 2]


In [93]:
source_string = "Julia is awesome!"

println(findfirst("awesome", source_string))

10:16


In [94]:
if contains(source_string, "Julia")
    println("Julia is indeed awesome")
end

Julia is indeed awesome


In [95]:
source_string = replace(source_string, "is" => "really is very")

"Julia really is very awesome!"

In [96]:
words = split(source_string, " ")

5-element Vector{SubString{String}}:
 "Julia"
 "really"
 "is"
 "very"
 "awesome!"

In [97]:
sentence = join(words, " ")

"Julia really is very awesome!"

In [98]:
phrase_end = findfirst("is ", sentence)
sentence = sentence[1:maximum(phrase_end)] * "a great language!"

"Julia really is a great language!"

In [99]:
sample_dct = Dict(:A => [1, 2, 3], :B => [1, 2, 3])
sample_arr = [5, 1, 3, 8, 4]

println(sample_dct)
delete!(sample_dct, :A)
println(sample_dct)

println(sample_arr)
deleteat!(sample_arr, 1)
println(sample_arr)

Dict(:A => [1, 2, 3], :B => [1, 2, 3])
Dict(:B => [1, 2, 3])
[5, 1, 3, 8, 4]
[1, 3, 8, 4]


In [100]:
filter(pair -> pair[1] == :B, sample_dct)

Dict{Symbol, Vector{Int64}} with 1 entry:
  :B => [1, 2, 3]

In [101]:
filter(x -> x < 20 && x > 1, [5, 10, 2, 4, 6, 3, 7, 25, 65, 22, 33, 14, 22, 11, 4, 6, 32])

11-element Vector{Int64}:
  5
 10
  2
  4
  6
  3
  7
 14
 11
  4
  6

#### dataframes

In [102]:
using DataFrames

In [103]:
df = DataFrame(:age => [52, 22, 17, 28], :color => ["red", "orange", "blue", missing], 
    :height => [5, 8, 9, 2], :depth => [5.2, missing, 6.6, 3.2])

4×4 DataFrame
 Row │ age    color    height  depth     
     │ Int64  String?  Int64   Float64?  
─────┼───────────────────────────────────
   1 │    52  red           5        5.2
   2 │    22  orange        8  missing   
   3 │    17  blue          9        6.6
   4 │    28  missing       2        3.2

In [48]:
dropmissing!(df)

2×4 DataFrame
 Row │ age    color   height  depth   
     │ Int64  String  Int64   Float64 
─────┼────────────────────────────────
   1 │    52  red          5      5.2
   2 │    17  blue         9      6.6

In [49]:
copy = filter(row -> row[:color] == "red", df)

1×4 DataFrame
 Row │ age    color   height  depth   
     │ Int64  String  Int64   Float64 
─────┼────────────────────────────────
   1 │    52  red          5      5.2

In [50]:
indexed = df[1, 1]

52

In [51]:
df[!, Not(:height)]

2×3 DataFrame
 Row │ age    color   depth   
     │ Int64  String  Float64 
─────┼────────────────────────
   1 │    52  red         5.2
   2 │    17  blue        6.6

In [52]:
# using CSV; df = CSV.read("data/sample.csv", DataFrame)

In [53]:
module APIServer
using Toolips

main = route("/") do c::Connection
    write!(c, "response")
end

export start!, main
end

using Toolips

In [107]:
using Main.APIServer; start!(APIServer, "127.0.0.1":8000)

🌷 toolips> loaded router type: Vector{Toolips.Route{Connection}}
🌷 toolips> server listening at http://127.0.0.1:8000


      Active manifest files: 7 found
      Active artifact files: 8 found
      Active scratchspaces: 5 found
     Deleted no artifacts, repos, packages or scratchspaces
[ Info: Listening on: 127.0.0.1:8000, thread id: 1


|  pid |              process type |                  name | active |
| ----:| -------------------------:| ---------------------:| ------:|
| 1371 | ParametricProcesses.Async | Main.APIServer router |   true |


In [55]:
pkgversion(Toolips)

v"0.3.3"

In [108]:
response = get("http://127.0.0.1:8000")

"response"

In [109]:
kill!(APIServer)

[ Info: Server on 127.0.0.1:8000 closing
      Active manifest files: 7 found
      Active artifact files: 8 found
      Active scratchspaces: 5 found
     Deleted no artifacts, repos, packages or scratchspaces
