# Linear Algebra I/Arrays
Being that Julia is a Scientific computing language that is known for its numerical calculation speeds, linear algebra is incredibly important to the language. As this is so, there are a an absolute boatload of methods and operators that are used for linear algebra in general. Today we will be going over some applications of linear algebra in Julia. This will be supplemented with some neat functions for working with Arrays in general
#### Regular linear algebra ' stuff'
- . operators
- dot
- cross
- factorize
- Diagonal
- BiDiagonal
- Array.T
- I
- Matrix
#### Array stuff
- length()
- Array{blank}
- getindex
- zeros
- ones
- trues
- falses
- fill/fill!
- size
- reshape
- cat, vcat, hcat
- findall
- findfirst, findlast, findnext
- accumulate
- cumsum
- repeat
- rot(dir)(degrees)
- eachrow/eachcol
- reverse
- enumerate
- select
- filter
- BitArray
- insert!
- push!
- append!
- deleteat!

In [20]:
x = [1, 2, 3, 4, 5]
length(x)
5

5

In [21]:
size(x)

(5,)

In [22]:
reshape(x, (5, 1))

5×1 Matrix{Int64}:
 1
 2
 3
 4
 5

In [23]:
getindex(x, 1)

1

In [24]:
x[1]

1

In [25]:
setindex!(x, 1, 2)

5-element Vector{Int64}:
 1
 1
 3
 4
 5

In [26]:
x[2] = 1

1

In [27]:
x = [7, 5, 4]

3-element Vector{Int64}:
 7
 5
 4

In [28]:
println(x)

[7, 5, 4]


In [29]:
push!(x, 5)

4-element Vector{Int64}:
 7
 5
 4
 5

In [30]:
append!(x, 5)

5-element Vector{Int64}:
 7
 5
 4
 5
 5

In [31]:
deleteat!(x, 4)

4-element Vector{Int64}:
 7
 5
 4
 5

In [32]:
findall("r", "rut roh, raggy")

3-element Vector{UnitRange{Int64}}:
 1:1
 5:5
 10:10

In [33]:
findall(x -> x == 5, x)

2-element Vector{Int64}:
 2
 4

In [34]:
findnext("a", "hello how are you", 1)

11:11

In [35]:
findfirst()
findlast()

LoadError: MethodError: no method matching findfirst()
Closest candidates are:
  findfirst(::Union{Base.Fix2{typeof(==), Int64}, Base.Fix2{typeof(isequal), Int64}}, ::Base.OneTo{Int64}) at /opt/julia-1.6.3/julia-1.6.3/share/julia/base/array.jl:2005
  findfirst(::Union{Base.Fix2{typeof(==), T}, Base.Fix2{typeof(isequal), T}}, ::AbstractUnitRange) where T<:Integer at /opt/julia-1.6.3/julia-1.6.3/share/julia/base/array.jl:2008
  findfirst(::Union{Base.Fix2{typeof(==), T}, Base.Fix2{typeof(isequal), T}}, ::StepRange{T, S}) where {T, S} at /opt/julia-1.6.3/julia-1.6.3/share/julia/base/array.jl:2011
  ...

In [36]:
maximum(x)

7

In [37]:
minimum(x)

4

In [38]:
collect(x)

4-element Vector{Int64}:
 7
 5
 4
 5

In [39]:
# calls iterate()
for i in x
    println(i)
end

7
5
4
5


In [41]:
for (n, i) in enumerate(x)
    println(n => i)
end

1 => 7
2 => 5
3 => 4
4 => 5


In [42]:
reverse(x)

4-element Vector{Int64}:
 5
 4
 5
 7

In [43]:
sort(x)

4-element Vector{Int64}:
 4
 5
 5
 7

In [46]:
x = [1 5 4; 5 6 9]

2×3 Matrix{Int64}:
 1  5  4
 5  6  9

In [48]:
hcat([1, 5, 4], [5, 6, 9])

3×2 Matrix{Int64}:
 1  5
 5  6
 4  9

In [49]:
vcat([1, 5, 4], [5, 6, 9])

6-element Vector{Int64}:
 1
 5
 4
 5
 6
 9

In [50]:
size(x)

(2, 3)

In [56]:
x .+ x

2×3 Matrix{Int64}:
  2  10   8
 10  12  18

In [57]:
x .* x

2×3 Matrix{Int64}:
  1  25  16
 25  36  81

In [58]:
x ./ x

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [59]:
x .^ 2

2×3 Matrix{Int64}:
  1  25  16
 25  36  81

In [53]:
using LinearAlgebra

In [61]:
transpose(x)


3×2 transpose(::Matrix{Int64}) with eltype Int64:
 1  5
 5  6
 4  9

In [60]:
dot(x, x)

184